// @generated from butuzov/mirror checkers_*.go (EqualFold casing fixed).
use super::{Violation, ViolationKind, BYTES, RUNE, STRINGS};

pub(super) fn all_violations() -> Vec<Violation> {
    vec![
        Violation {
            kind: ViolationKind::Function,
            args: &[0, 1],
            args_type: None,
            targets: STRINGS,
            package: "strings",
            alt_package: Some("bytes"),
            struct_name: None,
            caller: "Compare",
            alt_caller: "Compare",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0, 1],
            args_type: None,
            targets: STRINGS,
            package: "strings",
            alt_package: Some("bytes"),
            struct_name: None,
            caller: "Contains",
            alt_caller: "Contains",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0],
            args_type: None,
            targets: STRINGS,
            package: "strings",
            alt_package: Some("bytes"),
            struct_name: None,
            caller: "ContainsAny",
            alt_caller: "ContainsAny",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0],
            args_type: None,
            targets: STRINGS,
            package: "strings",
            alt_package: Some("bytes"),
            struct_name: None,
            caller: "ContainsRune",
            alt_caller: "ContainsRune",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0, 1],
            args_type: None,
            targets: STRINGS,
            package: "strings",
            alt_package: Some("bytes"),
            struct_name: None,
            caller: "Count",
            alt_caller: "Count",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0, 1],
            args_type: None,
            targets: STRINGS,
            package: "strings",
            alt_package: Some("bytes"),
            struct_name: None,
            caller: "EqualFold",
            alt_caller: "EqualFold",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0, 1],
            args_type: None,
            targets: STRINGS,
            package: "strings",
            alt_package: Some("bytes"),
            struct_name: None,
            caller: "HasPrefix",
            alt_caller: "HasPrefix",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0, 1],
            args_type: None,
            targets: STRINGS,
            package: "strings",
            alt_package: Some("bytes"),
            struct_name: None,
            caller: "HasSuffix",
            alt_caller: "HasSuffix",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0, 1],
            args_type: None,
            targets: STRINGS,
            package: "strings",
            alt_package: Some("bytes"),
            struct_name: None,
            caller: "Index",
            alt_caller: "Index",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0],
            args_type: None,
            targets: STRINGS,
            package: "strings",
            alt_package: Some("bytes"),
            struct_name: None,
            caller: "IndexAny",
            alt_caller: "IndexAny",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0],
            args_type: None,
            targets: STRINGS,
            package: "strings",
            alt_package: Some("bytes"),
            struct_name: None,
            caller: "IndexByte",
            alt_caller: "IndexByte",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0],
            args_type: None,
            targets: STRINGS,
            package: "strings",
            alt_package: Some("bytes"),
            struct_name: None,
            caller: "IndexFunc",
            alt_caller: "IndexFunc",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0],
            args_type: None,
            targets: STRINGS,
            package: "strings",
            alt_package: Some("bytes"),
            struct_name: None,
            caller: "IndexRune",
            alt_caller: "IndexRune",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0, 1],
            args_type: None,
            targets: STRINGS,
            package: "strings",
            alt_package: Some("bytes"),
            struct_name: None,
            caller: "LastIndex",
            alt_caller: "LastIndex",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0],
            args_type: None,
            targets: STRINGS,
            package: "strings",
            alt_package: Some("bytes"),
            struct_name: None,
            caller: "LastIndexAny",
            alt_caller: "LastIndexAny",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0],
            args_type: None,
            targets: STRINGS,
            package: "strings",
            alt_package: Some("bytes"),
            struct_name: None,
            caller: "LastIndexByte",
            alt_caller: "LastIndexByte",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0],
            args_type: None,
            targets: STRINGS,
            package: "strings",
            alt_package: Some("bytes"),
            struct_name: None,
            caller: "LastIndexFunc",
            alt_caller: "LastIndexFunc",
        },
        Violation {
            kind: ViolationKind::Method,
            args: &[0],
            args_type: None,
            targets: BYTES,
            package: "strings",
            alt_package: None,
            struct_name: Some("Builder"),
            caller: "Write",
            alt_caller: "WriteString",
        },
        Violation {
            kind: ViolationKind::Method,
            args: &[0],
            args_type: None,
            targets: STRINGS,
            package: "strings",
            alt_package: None,
            struct_name: Some("Builder"),
            caller: "WriteString",
            alt_caller: "Write",
        },
        Violation {
            kind: ViolationKind::Method,
            args: &[0],
            args_type: Some(RUNE),
            targets: STRINGS,
            package: "strings",
            alt_package: None,
            struct_name: Some("Builder"),
            caller: "WriteString",
            alt_caller: "WriteRune",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0],
            args_type: None,
            targets: BYTES,
            package: "bytes",
            alt_package: None,
            struct_name: None,
            caller: "NewBuffer",
            alt_caller: "NewBufferString",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0],
            args_type: None,
            targets: STRINGS,
            package: "bytes",
            alt_package: None,
            struct_name: None,
            caller: "NewBufferString",
            alt_caller: "NewBuffer",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0, 1],
            args_type: None,
            targets: BYTES,
            package: "bytes",
            alt_package: Some("strings"),
            struct_name: None,
            caller: "Compare",
            alt_caller: "Compare",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0, 1],
            args_type: None,
            targets: BYTES,
            package: "bytes",
            alt_package: Some("strings"),
            struct_name: None,
            caller: "Contains",
            alt_caller: "Contains",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0],
            args_type: None,
            targets: BYTES,
            package: "bytes",
            alt_package: Some("strings"),
            struct_name: None,
            caller: "ContainsAny",
            alt_caller: "ContainsAny",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0],
            args_type: None,
            targets: BYTES,
            package: "bytes",
            alt_package: Some("strings"),
            struct_name: None,
            caller: "ContainsRune",
            alt_caller: "ContainsRune",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0, 1],
            args_type: None,
            targets: BYTES,
            package: "bytes",
            alt_package: Some("strings"),
            struct_name: None,
            caller: "Count",
            alt_caller: "Count",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0, 1],
            args_type: None,
            targets: BYTES,
            package: "bytes",
            alt_package: Some("strings"),
            struct_name: None,
            caller: "EqualFold",
            alt_caller: "EqualFold",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0, 1],
            args_type: None,
            targets: BYTES,
            package: "bytes",
            alt_package: Some("strings"),
            struct_name: None,
            caller: "HasPrefix",
            alt_caller: "HasPrefix",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0, 1],
            args_type: None,
            targets: BYTES,
            package: "bytes",
            alt_package: Some("strings"),
            struct_name: None,
            caller: "HasSuffix",
            alt_caller: "HasSuffix",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0, 1],
            args_type: None,
            targets: BYTES,
            package: "bytes",
            alt_package: Some("strings"),
            struct_name: None,
            caller: "Index",
            alt_caller: "Index",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0],
            args_type: None,
            targets: BYTES,
            package: "bytes",
            alt_package: Some("strings"),
            struct_name: None,
            caller: "IndexAny",
            alt_caller: "IndexAny",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0],
            args_type: None,
            targets: BYTES,
            package: "bytes",
            alt_package: Some("strings"),
            struct_name: None,
            caller: "IndexByte",
            alt_caller: "IndexByte",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0],
            args_type: None,
            targets: BYTES,
            package: "bytes",
            alt_package: Some("strings"),
            struct_name: None,
            caller: "IndexFunc",
            alt_caller: "IndexFunc",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0],
            args_type: None,
            targets: BYTES,
            package: "bytes",
            alt_package: Some("strings"),
            struct_name: None,
            caller: "IndexRune",
            alt_caller: "IndexRune",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0, 1],
            args_type: None,
            targets: BYTES,
            package: "bytes",
            alt_package: Some("strings"),
            struct_name: None,
            caller: "LastIndex",
            alt_caller: "LastIndex",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0],
            args_type: None,
            targets: BYTES,
            package: "bytes",
            alt_package: Some("strings"),
            struct_name: None,
            caller: "LastIndexAny",
            alt_caller: "LastIndexAny",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0],
            args_type: None,
            targets: BYTES,
            package: "bytes",
            alt_package: Some("strings"),
            struct_name: None,
            caller: "LastIndexByte",
            alt_caller: "LastIndexByte",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0],
            args_type: None,
            targets: BYTES,
            package: "bytes",
            alt_package: Some("strings"),
            struct_name: None,
            caller: "LastIndexFunc",
            alt_caller: "LastIndexFunc",
        },
        Violation {
            kind: ViolationKind::Method,
            args: &[0],
            args_type: None,
            targets: BYTES,
            package: "bytes",
            alt_package: None,
            struct_name: Some("Buffer"),
            caller: "Write",
            alt_caller: "WriteString",
        },
        Violation {
            kind: ViolationKind::Method,
            args: &[0],
            args_type: None,
            targets: STRINGS,
            package: "bytes",
            alt_package: None,
            struct_name: Some("Buffer"),
            caller: "WriteString",
            alt_caller: "Write",
        },
        Violation {
            kind: ViolationKind::Method,
            args: &[0],
            args_type: Some(RUNE),
            targets: STRINGS,
            package: "bytes",
            alt_package: None,
            struct_name: Some("Buffer"),
            caller: "WriteString",
            alt_caller: "WriteRune",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[1],
            args_type: None,
            targets: BYTES,
            package: "regexp",
            alt_package: None,
            struct_name: None,
            caller: "Match",
            alt_caller: "MatchString",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[1],
            args_type: None,
            targets: STRINGS,
            package: "regexp",
            alt_package: None,
            struct_name: None,
            caller: "MatchString",
            alt_caller: "Match",
        },
        Violation {
            kind: ViolationKind::Method,
            args: &[0],
            args_type: None,
            targets: BYTES,
            package: "regexp",
            alt_package: None,
            struct_name: Some("Regexp"),
            caller: "Match",
            alt_caller: "MatchString",
        },
        Violation {
            kind: ViolationKind::Method,
            args: &[0],
            args_type: None,
            targets: STRINGS,
            package: "regexp",
            alt_package: None,
            struct_name: Some("Regexp"),
            caller: "MatchString",
            alt_caller: "Match",
        },
        Violation {
            kind: ViolationKind::Method,
            args: &[0],
            args_type: None,
            targets: BYTES,
            package: "regexp",
            alt_package: None,
            struct_name: Some("Regexp"),
            caller: "FindAllIndex",
            alt_caller: "FindAllStringIndex",
        },
        Violation {
            kind: ViolationKind::Method,
            args: &[0],
            args_type: None,
            targets: STRINGS,
            package: "regexp",
            alt_package: None,
            struct_name: Some("Regexp"),
            caller: "FindAllStringIndex",
            alt_caller: "FindAllIndex",
        },
        Violation {
            kind: ViolationKind::Method,
            args: &[0],
            args_type: None,
            targets: BYTES,
            package: "regexp",
            alt_package: None,
            struct_name: Some("Regexp"),
            caller: "FindAllSubmatchIndex",
            alt_caller: "FindAllStringSubmatchIndex",
        },
        Violation {
            kind: ViolationKind::Method,
            args: &[0],
            args_type: None,
            targets: STRINGS,
            package: "regexp",
            alt_package: None,
            struct_name: Some("Regexp"),
            caller: "FindAllStringSubmatchIndex",
            alt_caller: "FindAllSubmatchIndex",
        },
        Violation {
            kind: ViolationKind::Method,
            args: &[0],
            args_type: None,
            targets: BYTES,
            package: "regexp",
            alt_package: None,
            struct_name: Some("Regexp"),
            caller: "FindIndex",
            alt_caller: "FindStringIndex",
        },
        Violation {
            kind: ViolationKind::Method,
            args: &[0],
            args_type: None,
            targets: STRINGS,
            package: "regexp",
            alt_package: None,
            struct_name: Some("Regexp"),
            caller: "FindStringIndex",
            alt_caller: "FindIndex",
        },
        Violation {
            kind: ViolationKind::Method,
            args: &[0],
            args_type: None,
            targets: BYTES,
            package: "regexp",
            alt_package: None,
            struct_name: Some("Regexp"),
            caller: "FindSubmatchIndex",
            alt_caller: "FindStringSubmatchIndex",
        },
        Violation {
            kind: ViolationKind::Method,
            args: &[0],
            args_type: None,
            targets: STRINGS,
            package: "regexp",
            alt_package: None,
            struct_name: Some("Regexp"),
            caller: "FindStringSubmatchIndex",
            alt_caller: "FindSubmatchIndex",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0],
            args_type: None,
            targets: BYTES,
            package: "unicode/utf8",
            alt_package: None,
            struct_name: None,
            caller: "Valid",
            alt_caller: "ValidString",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0],
            args_type: None,
            targets: STRINGS,
            package: "unicode/utf8",
            alt_package: None,
            struct_name: None,
            caller: "ValidString",
            alt_caller: "Valid",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0],
            args_type: None,
            targets: BYTES,
            package: "unicode/utf8",
            alt_package: None,
            struct_name: None,
            caller: "FullRune",
            alt_caller: "FullRuneInString",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0],
            args_type: None,
            targets: STRINGS,
            package: "unicode/utf8",
            alt_package: None,
            struct_name: None,
            caller: "FullRuneInString",
            alt_caller: "FullRune",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0],
            args_type: None,
            targets: BYTES,
            package: "unicode/utf8",
            alt_package: None,
            struct_name: None,
            caller: "RuneCount",
            alt_caller: "RuneCountInString",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0],
            args_type: None,
            targets: STRINGS,
            package: "unicode/utf8",
            alt_package: None,
            struct_name: None,
            caller: "RuneCountInString",
            alt_caller: "RuneCount",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0],
            args_type: None,
            targets: BYTES,
            package: "unicode/utf8",
            alt_package: None,
            struct_name: None,
            caller: "DecodeLastRune",
            alt_caller: "DecodeLastRuneInString",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0],
            args_type: None,
            targets: STRINGS,
            package: "unicode/utf8",
            alt_package: None,
            struct_name: None,
            caller: "DecodeLastRuneInString",
            alt_caller: "DecodeLastRune",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0],
            args_type: None,
            targets: BYTES,
            package: "unicode/utf8",
            alt_package: None,
            struct_name: None,
            caller: "DecodeRune",
            alt_caller: "DecodeRuneInString",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[0],
            args_type: None,
            targets: STRINGS,
            package: "unicode/utf8",
            alt_package: None,
            struct_name: None,
            caller: "DecodeRuneInString",
            alt_caller: "DecodeRune",
        },
        Violation {
            kind: ViolationKind::Method,
            args: &[0],
            args_type: None,
            targets: BYTES,
            package: "os",
            alt_package: None,
            struct_name: Some("File"),
            caller: "Write",
            alt_caller: "WriteString",
        },
        Violation {
            kind: ViolationKind::Method,
            args: &[0],
            args_type: None,
            targets: STRINGS,
            package: "os",
            alt_package: None,
            struct_name: Some("File"),
            caller: "WriteString",
            alt_caller: "Write",
        },
        Violation {
            kind: ViolationKind::Method,
            args: &[0],
            args_type: None,
            targets: BYTES,
            package: "bufio",
            alt_package: None,
            struct_name: Some("Writer"),
            caller: "Write",
            alt_caller: "WriteString",
        },
        Violation {
            kind: ViolationKind::Method,
            args: &[0],
            args_type: None,
            targets: STRINGS,
            package: "bufio",
            alt_package: None,
            struct_name: Some("Writer"),
            caller: "WriteString",
            alt_caller: "Write",
        },
        Violation {
            kind: ViolationKind::Method,
            args: &[0],
            args_type: Some(RUNE),
            targets: STRINGS,
            package: "bufio",
            alt_package: None,
            struct_name: Some("Writer"),
            caller: "WriteString",
            alt_caller: "WriteRune",
        },
        Violation {
            kind: ViolationKind::Method,
            args: &[0],
            args_type: None,
            targets: BYTES,
            package: "net/http/httptest",
            alt_package: None,
            struct_name: Some("ResponseRecorder"),
            caller: "Write",
            alt_caller: "WriteString",
        },
        Violation {
            kind: ViolationKind::Method,
            args: &[0],
            args_type: None,
            targets: STRINGS,
            package: "net/http/httptest",
            alt_package: None,
            struct_name: Some("ResponseRecorder"),
            caller: "WriteString",
            alt_caller: "Write",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[1],
            args_type: None,
            targets: BYTES,
            package: "hash/maphash",
            alt_package: None,
            struct_name: None,
            caller: "Bytes",
            alt_caller: "String",
        },
        Violation {
            kind: ViolationKind::Function,
            args: &[1],
            args_type: None,
            targets: STRINGS,
            package: "hash/maphash",
            alt_package: None,
            struct_name: None,
            caller: "String",
            alt_caller: "Bytes",
        },
        Violation {
            kind: ViolationKind::Method,
            args: &[0],
            args_type: None,
            targets: BYTES,
            package: "hash/maphash",
            alt_package: None,
            struct_name: Some("Hash"),
            caller: "Write",
            alt_caller: "WriteString",
        },
        Violation {
            kind: ViolationKind::Method,
            args: &[0],
            args_type: None,
            targets: STRINGS,
            package: "hash/maphash",
            alt_package: None,
            struct_name: Some("Hash"),
            caller: "WriteString",
            alt_caller: "Write",
        },
    ]
}
