//! Port of [`github.com/ghostiam/protogetter`](https://github.com/ghostiam/protogetter)
//! (golangci-lint wrapper in `pkg/golinters/protogetter`).
//!
//! Reports direct reads from protobuf message fields where a generated getter
//! (`GetXxx()`) should be used instead, e.g. `msg.Name` → `msg.GetName()`.
//!
//! A type is treated as a proto message when it has a `ProtoReflect` method
//! (protobuf v2) or a `ProtoMessage` method (v1) — matching upstream
//! `isProtoMessage`. Types that additionally expose `MarshalToSizedBuffer`
//! (protoc-gen-gogo) are skipped because their getters may be unsafe.
//!
//! Write contexts are skipped via a position filter: assignment LHS,
//! `x++`/`x--`, and `&x.Field` (address-of, most likely a write through the
//! pointer such as `sql.Scan`).
//!
//! DEFERRED (see DEVELOPMENT.md R13): proto2 pointer refinements
//! (`getterResultHasPointer`, StarExpr getter-returns-value, nil comparisons),
//! `append`/optional-proto argument filtering, `DeclStmt`/`ReturnStmt`/
//! `KeyValueExpr` handling, generated-file skip by non-protoc prefixes, and
//! SuggestedFix emission.

use std::collections::HashSet;
use std::sync::OnceLock;

use guff::ast::{Expr, Ident};
use guff::parser::{parse_file, PARSE_COMMENTS};
use guff::position::FileSet;
use guff::token::Token;
use guff::walk::{preorder, NodeRef};
use guff_analysis::passes::inspect;
use guff_analysis::{AnalysisResult, Analyzer, Pass, RunError, RunFn};
use guff_types::alias::unalias_readonly;
use guff_types::arena::{TypeData, TypeId};
use guff_types::named::{named_method, named_num_methods};
use guff_types::pointer::pointer_elem;

/// Prefixes of `Code generated by …` markers that upstream always skips.
const PROTOC_PREFIXES: &[&str] = &[
    "Code generated by protoc-gen-go",
    "Code generated by protoc-gen-go-grpc",
    "Code generated by protoc-gen-grpc-gateway",
];

/// Returns the named type behind `expr`'s type, dereferencing one pointer.
///
/// Port of `typesNamed`.
fn expr_named_type(pass: &Pass<'_>, expr: &Expr) -> Option<TypeId> {
    let info = pass.types_info()?;
    let artifacts = pass.pkg().type_artifacts.as_ref()?;
    let t = info.types.get(&expr.id())?.typ;
    let t = unalias_readonly(&artifacts.types, t);
    let t = match artifacts.types.get(t) {
        TypeData::Pointer(_) => {
            let elem = pointer_elem(&artifacts.types, t);
            unalias_readonly(&artifacts.types, elem)
        }
        _ => t,
    };
    match artifacts.types.get(t) {
        TypeData::Named(_) => Some(t),
        _ => None,
    }
}

/// Port of `methodIsExists`: whether the named type behind `expr` declares a
/// method named `name` (explicitly declared methods only, like
/// `types.Named.NumMethods`).
fn method_exists(pass: &Pass<'_>, expr: &Expr, name: &str) -> bool {
    let Some(named) = expr_named_type(pass, expr) else {
        return false;
    };
    let Some(artifacts) = pass.pkg().type_artifacts.as_ref() else {
        return false;
    };
    let n = named_num_methods(&artifacts.types, named);
    for i in 0..n {
        let m = named_method(&artifacts.types, named, i);
        if m.name(&artifacts.objects) == name {
            return true;
        }
    }
    false
}

/// Port of `isProtoMessage`.
fn is_proto_message(pass: &Pass<'_>, expr: &Expr) -> bool {
    if method_exists(pass, expr, "ProtoReflect") {
        return true;
    }
    if method_exists(pass, expr, "ProtoMessage") {
        return !method_exists(pass, expr, "MarshalToSizedBuffer");
    }
    false
}

/// Accumulates the original (`from`) and suggested (`to`) source strings.
#[derive(Default)]
struct Rewrite {
    from: String,
    to: String,
}

impl Rewrite {
    fn write(&mut self, s: &str) {
        self.from.push_str(s);
        self.to.push_str(s);
    }
    fn skipped(&self) -> bool {
        self.from == self.to
    }
}

/// Port of the `*ast.SelectorExpr` arm of `processInner`.
fn process_inner_sel(
    pass: &Pass<'_>,
    x: &Expr,
    sel: &Ident,
    filtered: &HashSet<i64>,
    rw: &mut Rewrite,
) {
    process_inner(pass, x, filtered, rw);
    rw.write(".");
    if method_exists(pass, x, &format!("Get{}", sel.name))
        && !filtered.contains(&sel.pos().0)
        && is_proto_message(pass, x)
    {
        rw.from.push_str(&sel.name);
        rw.to.push_str(&format!("Get{}()", sel.name));
        return;
    }
    rw.write(&sel.name);
}

/// Port of `processInner` (recursive source reconstruction with getter swap).
fn process_inner(pass: &Pass<'_>, e: &Expr, filtered: &HashSet<i64>, rw: &mut Rewrite) {
    match e {
        Expr::Ident(id) => rw.write(&id.name),
        Expr::BasicLit(l) => rw.write(&l.value),
        Expr::SelectorExpr(s) => process_inner_sel(pass, &s.x, &s.sel, filtered, rw),
        Expr::CallExpr(c) => {
            process_inner(pass, &c.fun, filtered, rw);
            rw.write("(");
            for (i, arg) in c.args.iter().enumerate() {
                if i > 0 {
                    rw.write(",");
                }
                process_inner(pass, arg, filtered, rw);
            }
            rw.write(")");
        }
        Expr::IndexExpr(ix) => {
            process_inner(pass, &ix.x, filtered, rw);
            rw.write("[");
            process_inner(pass, &ix.index, filtered, rw);
            rw.write("]");
        }
        Expr::ParenExpr(p) => {
            rw.write("(");
            process_inner(pass, &p.x, filtered, rw);
            rw.write(")");
        }
        Expr::StarExpr(st) => {
            rw.write("*");
            process_inner(pass, &st.x, filtered, rw);
        }
        Expr::UnaryExpr(u) if u.op == Token::AND => rw.write(&render_expr(e)),
        Expr::UnaryExpr(u) => {
            rw.write(u.op.as_str());
            process_inner(pass, &u.x, filtered, rw);
        }
        Expr::BinaryExpr(b) => {
            process_inner(pass, &b.x, filtered, rw);
            rw.write(b.op.as_str());
            process_inner(pass, &b.y, filtered, rw);
        }
        // CompositeLit / TypeAssertExpr / ArrayType / FuncLit / SliceExpr /
        // MapType — keep as-is (upstream uses go/format).
        other => rw.write(&render_expr(other)),
    }
}

/// Best-effort source rendering for leaf/opaque expressions.
fn render_expr(expr: &Expr) -> String {
    match expr {
        Expr::Ident(id) => id.name.clone(),
        Expr::BasicLit(l) => l.value.clone(),
        Expr::ParenExpr(p) => format!("({})", render_expr(&p.x)),
        Expr::StarExpr(s) => format!("*{}", render_expr(&s.x)),
        Expr::UnaryExpr(u) => format!("{}{}", u.op.as_str(), render_expr(&u.x)),
        Expr::BinaryExpr(b) => {
            format!("{}{}{}", render_expr(&b.x), b.op.as_str(), render_expr(&b.y))
        }
        Expr::SelectorExpr(s) => format!("{}.{}", render_expr(&s.x), s.sel.name),
        Expr::IndexExpr(ix) => format!("{}[{}]", render_expr(&ix.x), render_expr(&ix.index)),
        Expr::CallExpr(c) => {
            let mut s = render_expr(&c.fun);
            s.push('(');
            for (i, a) in c.args.iter().enumerate() {
                if i > 0 {
                    s.push(',');
                }
                s.push_str(&render_expr(a));
            }
            s.push(')');
            s
        }
        _ => String::new(),
    }
}

/// Whether the file at `path` was generated by protoc (skipped by default).
fn is_protoc_generated(path: &std::path::Path) -> bool {
    let Ok(src) = std::fs::read(path) else {
        return false;
    };
    let Some(name) = path.file_name().and_then(|s| s.to_str()) else {
        return false;
    };
    let fset = FileSet::new();
    let Ok(file) = parse_file(&fset, name, &src, PARSE_COMMENTS) else {
        return false;
    };
    let Some(first) = file.comments.first() else {
        return false;
    };
    let text = first.text();
    PROTOC_PREFIXES
        .iter()
        .any(|prefix| text.starts_with(prefix))
}

fn run(pass: &mut Pass<'_>) -> Result<Option<AnalysisResult>, RunError> {
    let _ = pass
        .result_of::<inspect::InspectResult>(inspect::analyzer())
        .ok_or_else(|| "protogetter requires inspect analyzer".to_string())?;

    let mut filtered: HashSet<i64> = HashSet::new();
    let mut replaced: Vec<(i64, i64)> = Vec::new();
    let mut pending: Vec<(u32, String)> = Vec::new();

    for (i, file) in pass.files().iter().enumerate() {
        let path = pass
            .pkg()
            .compiled_go_files
            .get(i)
            .cloned()
            .or_else(|| pass.pkg().go_files.get(i).cloned());
        if let Some(path) = &path {
            if is_protoc_generated(path) {
                continue;
            }
        }

        preorder(NodeRef::File(file), |n| {
            match n {
                NodeRef::AssignStmt(a) => {
                    for lhs in &a.lhs {
                        filtered.insert(lhs.pos().0);
                        if let Expr::StarExpr(se) = lhs {
                            filtered.insert(se.x.pos().0);
                        }
                    }
                }
                NodeRef::IncDecStmt(s) => {
                    filtered.insert(s.x.pos().0);
                }
                NodeRef::UnaryExpr(u) if u.op == Token::AND => {
                    filtered.insert(u.x.pos().0);
                }
                NodeRef::SelectorExpr(sel) => {
                    let node_pos = sel.x.pos().0;
                    if filtered.contains(&node_pos) {
                        return true;
                    }
                    if !is_proto_message(pass, &sel.x) {
                        return true;
                    }
                    let mut rw = Rewrite::default();
                    process_inner_sel(pass, &sel.x, &sel.sel, &filtered, &mut rw);
                    if rw.skipped() {
                        return true;
                    }
                    let node_end = sel.sel.end().0;
                    if replaced
                        .iter()
                        .any(|&(s, e)| s <= node_pos && node_end <= e)
                    {
                        return true;
                    }
                    replaced.push((node_pos, node_end));
                    pending.push((
                        node_pos as u32,
                        format!(
                            "avoid direct access to proto field {}, use {} instead",
                            rw.from, rw.to
                        ),
                    ));
                }
                NodeRef::StarExpr(st) => {
                    // proto2 pointer field deref: `*msg.Field`.
                    let Expr::SelectorExpr(f) = st.x.as_ref() else {
                        return true;
                    };
                    let node_pos = st.star.0;
                    if filtered.contains(&node_pos) || filtered.contains(&f.x.pos().0) {
                        return true;
                    }
                    if !is_proto_message(pass, &f.x) {
                        return true;
                    }
                    let mut rw = Rewrite::default();
                    rw.from.push('*');
                    process_inner_sel(pass, &f.x, &f.sel, &filtered, &mut rw);
                    if rw.skipped() {
                        return true;
                    }
                    let node_end = f.sel.end().0;
                    if replaced
                        .iter()
                        .any(|&(s, e)| s <= node_pos && node_end <= e)
                    {
                        return true;
                    }
                    replaced.push((node_pos, node_end));
                    pending.push((
                        node_pos as u32,
                        format!(
                            "avoid direct access to proto field {}, use {} instead",
                            rw.from, rw.to
                        ),
                    ));
                }
                _ => {}
            }
            true
        });
    }

    for (pos, msg) in pending {
        pass.reportf(pos, &msg);
    }
    Ok(None)
}

pub fn analyzer() -> &'static Analyzer {
    static A: OnceLock<Analyzer> = OnceLock::new();
    A.get_or_init(|| Analyzer {
        name: "protogetter",
        doc: "Reports direct reads from proto message fields when getters should be used.",
        url: "https://github.com/ghostiam/protogetter",
        run: run as RunFn,
        run_despite_errors: false,
        requires: vec![inspect::analyzer()],
        fact_types: vec![],
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn protoc_prefixes_recognized() {
        assert!(PROTOC_PREFIXES
            .iter()
            .any(|p| "Code generated by protoc-gen-go. DO NOT EDIT.".starts_with(p)));
        assert!(!PROTOC_PREFIXES
            .iter()
            .any(|p| "Code generated by stringer".starts_with(p)));
    }

    #[test]
    fn rewrite_skipped_when_equal() {
        let mut rw = Rewrite::default();
        rw.write("m.Name");
        assert!(rw.skipped());
        rw.to.push_str("X");
        assert!(!rw.skipped());
    }
}
