//! Port of [`github.com/ghostiam/protogetter`](https://github.com/ghostiam/protogetter)
//! (golangci-lint wrapper in `pkg/golinters/protogetter`).
//!
//! Reports direct reads from protobuf message fields where a generated getter
//! (`GetXxx()`) should be used instead, e.g. `msg.Name` → `msg.GetName()`.
//!
//! A type is treated as a proto message when it has a `ProtoReflect` method
//! (protobuf v2) or a `ProtoMessage` method (v1) — matching upstream
//! `isProtoMessage`. Types that additionally expose `MarshalToSizedBuffer`
//! (protoc-gen-gogo) are skipped because their getters may be unsafe.
//!
//! Write contexts are skipped via a position filter: assignment LHS,
//! `x++`/`x--`, and `&x.Field` (address-of, most likely a write through the
//! pointer such as `sql.Scan`).
//!
//! `msg.Field == nil` is filtered too when `GetField` returns a non-pointer,
//! and the first argument of `append` is filtered — both as upstream does.
//!
//! A pointer target whose getter returns a value is filtered too: assigning
//! `u.GetNickname()` (a `string`) where a `*string` is wanted does not compile,
//! so upstream does not propose it.
//!
//! DEFERRED (see DEVELOPMENT.md R13): StarExpr getter-returns-value,
//! optional-proto argument filtering, `DeclStmt`/`ReturnStmt` handling,
//! generated-file skip by non-protoc prefixes, and SuggestedFix emission.

use std::collections::HashSet;
use std::sync::OnceLock;

use guff::ast::{Expr, Ident};
use guff::parser::{parse_file, PARSE_COMMENTS};
use guff::position::FileSet;
use guff::token::Token;
use guff::walk::{preorder, NodeRef};
use guff_analysis::passes::inspect;
use guff_analysis::{AnalysisResult, Analyzer, Pass, RunError, RunFn, Diagnostic, SuggestedFix, TextEdit};
use guff_types::alias::unalias_readonly;
use guff_types::arena::{TypeData, TypeId};
use guff_types::named::{named_method, named_num_methods};
use guff_types::pointer::pointer_elem;

/// Prefixes of `Code generated by …` markers that upstream always skips.
const PROTOC_PREFIXES: &[&str] = &[
    "Code generated by protoc-gen-go",
    "Code generated by protoc-gen-go-grpc",
    "Code generated by protoc-gen-grpc-gateway",
];

/// Returns the named type behind `expr`'s type, dereferencing one pointer.
///
/// Port of `typesNamed`, **including its blindness to aliases**:
///
/// ```go
/// ptr, ok := t.Underlying().(*types.Pointer)
/// if ok { t = ptr.Elem() }
/// named, ok := t.(*types.Named)   // a plain assertion — no Unalias
/// ```
///
/// Since Go 1.23 (`gotypesalias=1`) a type written through an alias is a
/// `*types.Alias`, and that assertion fails on it. So a message reached as
/// `*backend.WorkflowRuntimeState`, where `backend.WorkflowRuntimeState =
/// protos.WorkflowRuntimeState`, is not a proto message to protogetter at all —
/// no getters are suggested for any of its fields.
///
/// guff unaliased on both steps, which is the *correct* answer to the question
/// "what named type is this" and the wrong answer to "what does protogetter
/// do". dapr v1.18.3 reaches every durabletask message through such an alias:
/// golangci-lint reports zero protogetter findings on the whole repo, and guff
/// reported 54. The pointer step still uses the underlying type, as upstream
/// does, so an alias *for a pointer* is dereferenced there.
fn expr_named_type(pass: &Pass<'_>, expr: &Expr) -> Option<TypeId> {
    let info = pass.types_info()?;
    let artifacts = pass.pkg().type_artifacts.as_ref()?;
    let t = info.types.get(&expr.id())?.typ;
    let under = t.underlying(&artifacts.types);
    let t = match artifacts.types.get(under) {
        TypeData::Pointer(_) => pointer_elem(&artifacts.types, under),
        _ => t,
    };
    match artifacts.types.get(t) {
        TypeData::Named(_) => Some(t),
        _ => None,
    }
}

/// Port of `methodIsExists`: whether the named type behind `expr` declares a
/// method named `name` (explicitly declared methods only, like
/// `types.Named.NumMethods`).
fn method_exists(pass: &Pass<'_>, expr: &Expr, name: &str) -> bool {
    let Some(named) = expr_named_type(pass, expr) else {
        return false;
    };
    let Some(artifacts) = pass.pkg().type_artifacts.as_ref() else {
        return false;
    };
    let n = named_num_methods(&artifacts.types, named);
    for i in 0..n {
        let m = named_method(&artifacts.types, named, i);
        if m.name(&artifacts.objects) == name {
            return true;
        }
    }
    false
}

/// Upstream's `hasPointerKeyWithoutPointerGetter`: the place the value is going
/// is a pointer, and the getter hands back a value.
///
/// `Schedule: job.Schedule` in a `*pb.Job` literal is the shape — the field is
/// `*string`, `GetSchedule()` is `string`, and `Schedule: job.GetSchedule()`
/// does not compile. Upstream filters the position; a getter that *does* return
/// a pointer is reported as usual.
fn pointer_target_without_pointer_getter(
    pass: &Pass<'_>,
    target: &Expr,
    value: &guff::ast::SelectorExpr,
) -> bool {
    let Some(typ) = expr_or_object_type(pass, target) else {
        return false;
    };
    pointer_type_without_pointer_getter(pass, typ, value)
}

fn pointer_type_without_pointer_getter(
    pass: &Pass<'_>,
    target: guff_types::TypeId,
    value: &guff::ast::SelectorExpr,
) -> bool {
    let Some(artifacts) = pass.pkg().type_artifacts.as_ref() else {
        return false;
    };
    if !matches!(artifacts.types.get(target), TypeData::Pointer(_)) {
        return false;
    }
    getter_result_has_pointer(pass, &value.x, &value.sel.name) == Some(false)
}

/// The type of the struct field a composite-literal key names.
///
/// `types.Info.TypeOf` answers this from `Uses`, which records the field for a
/// keyed struct literal. guff's checker does not record those keys, so the
/// field is looked up in the literal's own struct type by name.
fn struct_field_type(
    pass: &Pass<'_>,
    lit_ty: guff_types::TypeId,
    name: &str,
) -> Option<guff_types::TypeId> {
    let artifacts = pass.pkg().type_artifacts.as_ref()?;
    let mut ty = guff_types::alias::unalias_readonly(&artifacts.types, lit_ty);
    if let TypeData::Pointer(p) = artifacts.types.get(ty) {
        ty = guff_types::alias::unalias_readonly(&artifacts.types, p.elem());
    }
    let under = ty.underlying(&artifacts.types);
    let TypeData::Struct(st) = artifacts.types.get(under) else {
        return None;
    };
    for i in 0..st.num_fields() {
        let field = st.field(i);
        if field.name(&artifacts.objects) == name {
            return field.typ(&artifacts.objects);
        }
    }
    None
}

/// The type of an expression, falling back to the object an identifier refers
/// to — a composite literal's field key has no recorded expression type, only a
/// `Uses` entry, and `types.Info.TypeOf` reads both.
fn expr_or_object_type(pass: &Pass<'_>, expr: &Expr) -> Option<guff_types::TypeId> {
    let info = pass.types_info()?;
    if let Some(tv) = info.types.get(&expr.id()) {
        return Some(tv.typ);
    }
    let Expr::Ident(id) = expr else {
        return None;
    };
    let artifacts = pass.pkg().type_artifacts.as_ref()?;
    let obj = info
        .uses
        .get(&id.id)
        .copied()
        .or_else(|| info.defs.get(&id.id).and_then(|o| *o))?;
    obj.typ(&artifacts.objects)
}

/// Port of `getterResultHasPointer`: does `Get<name>` on the named type behind
/// `expr` return a pointer?
///
/// `None` when the question cannot be answered (no named type, no such getter,
/// or a getter with no results) — upstream's `ok == false`, which is treated
/// the same as a pointer result.
fn getter_result_has_pointer(pass: &Pass<'_>, expr: &Expr, name: &str) -> Option<bool> {
    let named = expr_named_type(pass, expr)?;
    let artifacts = pass.pkg().type_artifacts.as_ref()?;
    let want = format!("Get{name}");
    let n = named_num_methods(&artifacts.types, named);
    for i in 0..n {
        let m = named_method(&artifacts.types, named, i);
        if m.name(&artifacts.objects) != want {
            continue;
        }
        let sig = m.typ(&artifacts.objects)?;
        let results = guff_types::signature::signature_results(&artifacts.types, sig);
        if guff_types::tuple::tuple_len(&artifacts.types, results) == 0 {
            return None;
        }
        let first_obj = guff_types::tuple::tuple_at(&artifacts.types, results?, 0);
        let first = first_obj.typ(&artifacts.objects)?;
        let first = unalias_readonly(&artifacts.types, first);
        return Some(matches!(
            artifacts.types.get(first),
            TypeData::Pointer(_)
        ));
    }
    None
}

/// Port of `isProtoMessage`.
fn is_proto_message(pass: &Pass<'_>, expr: &Expr) -> bool {
    if method_exists(pass, expr, "ProtoReflect") {
        return true;
    }
    if method_exists(pass, expr, "ProtoMessage") {
        return !method_exists(pass, expr, "MarshalToSizedBuffer");
    }
    false
}

/// Accumulates the original (`from`) and suggested (`to`) source strings.
#[derive(Default)]
struct Rewrite {
    from: String,
    to: String,
}

impl Rewrite {
    fn write(&mut self, s: &str) {
        self.from.push_str(s);
        self.to.push_str(s);
    }
    fn skipped(&self) -> bool {
        self.from == self.to
    }
}

/// Port of the `*ast.SelectorExpr` arm of `processInner`.
fn process_inner_sel(
    pass: &Pass<'_>,
    x: &Expr,
    sel: &Ident,
    filtered: &HashSet<i64>,
    rw: &mut Rewrite,
) {
    process_inner(pass, x, filtered, rw);
    rw.write(".");
    if method_exists(pass, x, &format!("Get{}", sel.name))
        && !filtered.contains(&sel.pos().0)
        && is_proto_message(pass, x)
    {
        rw.from.push_str(&sel.name);
        rw.to.push_str(&format!("Get{}()", sel.name));
        return;
    }
    rw.write(&sel.name);
}

/// Port of `processInner` (recursive source reconstruction with getter swap).
fn process_inner(pass: &Pass<'_>, e: &Expr, filtered: &HashSet<i64>, rw: &mut Rewrite) {
    match e {
        Expr::Ident(id) => rw.write(&id.name),
        Expr::BasicLit(l) => rw.write(&l.value),
        Expr::SelectorExpr(s) => process_inner_sel(pass, &s.x, &s.sel, filtered, rw),
        Expr::CallExpr(c) => {
            process_inner(pass, &c.fun, filtered, rw);
            rw.write("(");
            for (i, arg) in c.args.iter().enumerate() {
                if i > 0 {
                    rw.write(",");
                }
                process_inner(pass, arg, filtered, rw);
            }
            rw.write(")");
        }
        Expr::IndexExpr(ix) => {
            process_inner(pass, &ix.x, filtered, rw);
            rw.write("[");
            process_inner(pass, &ix.index, filtered, rw);
            rw.write("]");
        }
        Expr::ParenExpr(p) => {
            rw.write("(");
            process_inner(pass, &p.x, filtered, rw);
            rw.write(")");
        }
        Expr::StarExpr(st) => {
            rw.write("*");
            process_inner(pass, &st.x, filtered, rw);
        }
        Expr::UnaryExpr(u) if u.op == Token::AND => rw.write(&render_expr(e)),
        Expr::UnaryExpr(u) => {
            rw.write(u.op.as_str());
            process_inner(pass, &u.x, filtered, rw);
        }
        Expr::BinaryExpr(b) => {
            process_inner(pass, &b.x, filtered, rw);
            rw.write(b.op.as_str());
            process_inner(pass, &b.y, filtered, rw);
        }
        // CompositeLit / TypeAssertExpr / ArrayType / FuncLit / SliceExpr /
        // MapType — keep as-is (upstream uses go/format).
        other => rw.write(&render_expr(other)),
    }
}

/// Best-effort source rendering for leaf/opaque expressions.
fn render_expr(expr: &Expr) -> String {
    match expr {
        Expr::Ident(id) => id.name.clone(),
        Expr::BasicLit(l) => l.value.clone(),
        Expr::ParenExpr(p) => format!("({})", render_expr(&p.x)),
        Expr::StarExpr(s) => format!("*{}", render_expr(&s.x)),
        Expr::UnaryExpr(u) => format!("{}{}", u.op.as_str(), render_expr(&u.x)),
        Expr::BinaryExpr(b) => {
            format!("{}{}{}", render_expr(&b.x), b.op.as_str(), render_expr(&b.y))
        }
        Expr::SelectorExpr(s) => format!("{}.{}", render_expr(&s.x), s.sel.name),
        Expr::IndexExpr(ix) => format!("{}[{}]", render_expr(&ix.x), render_expr(&ix.index)),
        Expr::CallExpr(c) => {
            let mut s = render_expr(&c.fun);
            s.push('(');
            for (i, a) in c.args.iter().enumerate() {
                if i > 0 {
                    s.push(',');
                }
                s.push_str(&render_expr(a));
            }
            s.push(')');
            s
        }
        _ => String::new(),
    }
}

/// Whether the file at `path` was generated by protoc (skipped by default).
fn is_protoc_generated(path: &std::path::Path) -> bool {
    let Ok(src) = std::fs::read(path) else {
        return false;
    };
    let Some(name) = path.file_name().and_then(|s| s.to_str()) else {
        return false;
    };
    let fset = FileSet::new();
    let Ok(file) = parse_file(&fset, name, &src, PARSE_COMMENTS) else {
        return false;
    };
    let Some(first) = file.comments.first() else {
        return false;
    };
    let text = first.text();
    PROTOC_PREFIXES
        .iter()
        .any(|prefix| text.starts_with(prefix))
}

fn run(pass: &mut Pass<'_>) -> Result<Option<AnalysisResult>, RunError> {
    let _ = pass
        .result_of::<inspect::InspectResult>(inspect::analyzer())
        .ok_or_else(|| "protogetter requires inspect analyzer".to_string())?;

    let mut filtered: HashSet<i64> = HashSet::new();
    let mut replaced: Vec<(i64, i64)> = Vec::new();
    let mut pending: Vec<(u32, String, TextEdit)> = Vec::new();

    for (i, file) in pass.files().iter().enumerate() {
        let path = pass
            .pkg()
            .compiled_go_files
            .get(i)
            .cloned()
            .or_else(|| pass.pkg().go_files.get(i).cloned());
        if let Some(path) = &path {
            if is_protoc_generated(path) {
                continue;
            }
        }

        preorder(NodeRef::File(file), |n| {
            match n {
                NodeRef::AssignStmt(a) => {
                    for (i, lhs) in a.lhs.iter().enumerate() {
                        filtered.insert(lhs.pos().0);
                        if let Expr::StarExpr(se) = lhs {
                            filtered.insert(se.x.pos().0);
                        }
                        if let Some(Expr::SelectorExpr(se)) = a.rhs.get(i) {
                            if pointer_target_without_pointer_getter(pass, lhs, se) {
                                filtered.insert(se.x.pos().0);
                            }
                        }
                    }
                }
                // `&pb.Job{Schedule: job.Schedule}` where the *field* is
                // `*string` and `GetSchedule()` returns `string`: the getter
                // cannot be written there, so upstream filters the position
                // instead of proposing a rewrite that would not compile. dapr
                // fills sixteen optional proto fields this way.
                NodeRef::KeyValueExpr(kv) => {
                    if let Expr::SelectorExpr(se) = &*kv.value {
                        if pointer_target_without_pointer_getter(pass, &kv.key, se) {
                            filtered.insert(se.x.pos().0);
                        }
                    }
                }
                // Keyed *struct* literals go through the literal, because the
                // key names a field and guff's checker records no type for it.
                NodeRef::CompositeLit(lit) => {
                    let Some(lit_ty) = pass
                        .types_info()
                        .and_then(|i| i.types.get(&lit.id))
                        .map(|tv| tv.typ)
                    else {
                        return true;
                    };
                    for elt in &lit.elts {
                        let Expr::KeyValueExpr(kv) = elt else {
                            continue;
                        };
                        let (Expr::Ident(key), Expr::SelectorExpr(se)) =
                            (&*kv.key, &*kv.value)
                        else {
                            continue;
                        };
                        let Some(field_ty) = struct_field_type(pass, lit_ty, &key.name) else {
                            continue;
                        };
                        if pointer_type_without_pointer_getter(pass, field_ty, se) {
                            filtered.insert(se.x.pos().0);
                        }
                    }
                }
                NodeRef::IncDecStmt(s) => {
                    filtered.insert(s.x.pos().0);
                }
                NodeRef::UnaryExpr(u) if u.op == Token::AND => {
                    filtered.insert(u.x.pos().0);
                }
                // `append(msg.Field, x)` — the first argument is the slice
                // being grown, and rewriting it to `msg.GetField()` changes
                // what `append` may write in place. Upstream filters it unless
                // `replace-first-arg-in-append` is set, which golangci leaves
                // off by default (and guff does not expose yet).
                NodeRef::CallExpr(c)
                    if matches!(c.fun.as_ref(), Expr::Ident(id) if id.name == "append")
                        && !c.args.is_empty() =>
                {
                    filtered.insert(c.args[0].pos().0);
                }
                // `msg.Field == nil` / `!= nil`, when `GetField` returns
                // something that is not a pointer (a map, a slice), is a
                // question the getter answers identically, so upstream filters
                // the position rather than proposing a rewrite. A getter that
                // *does* return a pointer is left alone here and reported by
                // the SelectorExpr arm below — the asymmetry is upstream's.
                //
                // Upstream filters `x.X.Pos()`, the *left* operand, so the
                // reversed spelling `nil == msg.Field` filters the `nil` and
                // the field is still reported. That quirk is load-bearing:
                // guff already matched it, and only the common spelling was
                // wrong. dapr writes 80 of them (`if req.Metadata == nil`).
                NodeRef::BinaryExpr(b) if b.op == Token::EQL || b.op == Token::NEQ => {
                    let is_nil = |e: &Expr| matches!(e, Expr::Ident(id) if id.name == "nil");
                    let x_is_nil = is_nil(&b.x);
                    let y_is_nil = is_nil(&b.y);
                    if !x_is_nil && !y_is_nil {
                        return true;
                    }
                    let operand = if x_is_nil { &b.y } else { &b.x };
                    let Expr::SelectorExpr(se) = operand.as_ref() else {
                        return true;
                    };
                    if !is_proto_message(pass, &se.x) {
                        return true;
                    }
                    if getter_result_has_pointer(pass, &se.x, &se.sel.name) == Some(false) {
                        filtered.insert(b.x.pos().0);
                    }
                }
                NodeRef::SelectorExpr(sel) => {
                    let node_pos = sel.x.pos().0;
                    if filtered.contains(&node_pos) {
                        return true;
                    }
                    if !is_proto_message(pass, &sel.x) {
                        return true;
                    }
                    let mut rw = Rewrite::default();
                    process_inner_sel(pass, &sel.x, &sel.sel, &filtered, &mut rw);
                    if rw.skipped() {
                        return true;
                    }
                    let node_end = sel.sel.end().0;
                    if replaced
                        .iter()
                        .any(|&(s, e)| s <= node_pos && node_end <= e)
                    {
                        return true;
                    }
                    replaced.push((node_pos, node_end));
                    // The fix is the message's own second half: upstream
                    // replaces the node with `result.To`, the same string it
                    // formats into "use %s instead".
                    pending.push((
                        node_pos as u32,
                        format!(
                            "avoid direct access to proto field {}, use {} instead",
                            rw.from, rw.to
                        ),
                        TextEdit {
                            pos: node_pos as u32,
                            end: node_end as u32,
                            new_text: rw.to.clone(),
                        },
                    ));
                }
                NodeRef::StarExpr(st) => {
                    // proto2 pointer field deref: `*msg.Field`.
                    let Expr::SelectorExpr(f) = st.x.as_ref() else {
                        return true;
                    };
                    let node_pos = st.star.0;
                    if filtered.contains(&node_pos) || filtered.contains(&f.x.pos().0) {
                        return true;
                    }
                    if !is_proto_message(pass, &f.x) {
                        return true;
                    }
                    let mut rw = Rewrite::default();
                    rw.from.push('*');
                    process_inner_sel(pass, &f.x, &f.sel, &filtered, &mut rw);
                    if rw.skipped() {
                        return true;
                    }
                    let node_end = f.sel.end().0;
                    if replaced
                        .iter()
                        .any(|&(s, e)| s <= node_pos && node_end <= e)
                    {
                        return true;
                    }
                    replaced.push((node_pos, node_end));
                    // The fix is the message's own second half: upstream
                    // replaces the node with `result.To`, the same string it
                    // formats into "use %s instead".
                    pending.push((
                        node_pos as u32,
                        format!(
                            "avoid direct access to proto field {}, use {} instead",
                            rw.from, rw.to
                        ),
                        TextEdit {
                            pos: node_pos as u32,
                            end: node_end as u32,
                            new_text: rw.to.clone(),
                        },
                    ));
                }
                _ => {}
            }
            true
        });
    }

    for (pos, message, edit) in pending {
        pass.report(Diagnostic {
            pos,
            message,
            suggested_fixes: vec![SuggestedFix {
                message: String::new(),
                text_edits: vec![edit],
            }],
            ..Diagnostic::default()
        });
    }
    Ok(None)
}

pub fn analyzer() -> &'static Analyzer {
    static A: OnceLock<Analyzer> = OnceLock::new();
    A.get_or_init(|| Analyzer {
        name: "protogetter",
        doc: "Reports direct reads from proto message fields when getters should be used.",
        url: "https://github.com/ghostiam/protogetter",
        run: run as RunFn,
        run_despite_errors: false,
        requires: vec![inspect::analyzer()],
        fact_types: vec![],
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn protoc_prefixes_recognized() {
        assert!(PROTOC_PREFIXES
            .iter()
            .any(|p| "Code generated by protoc-gen-go. DO NOT EDIT.".starts_with(p)));
        assert!(!PROTOC_PREFIXES
            .iter()
            .any(|p| "Code generated by stringer".starts_with(p)));
    }

    #[test]
    fn rewrite_skipped_when_equal() {
        let mut rw = Rewrite::default();
        rw.write("m.Name");
        assert!(rw.skipped());
        rw.to.push_str("X");
        assert!(!rw.skipped());
    }
}
