// Generated by scripts/gen-doccomment-tables.go — DO NOT EDIT.
//
// The go1.26.5 standard library packages whose import path is a single element, and
// which therefore could not otherwise be named in a doc link (go/doc/comment's
// std.go). Upstream keeps this sorted and binary-searches it; so does
// `is_std_pkg`.

#[rustfmt::skip]
static STD_PKGS: &[&str] = &[
    "bufio", "bytes", "cmp", "context", "crypto", "embed",
    "encoding", "errors", "expvar", "flag", "fmt", "hash",
    "html", "image", "io", "iter", "log", "maps",
    "math", "mime", "net", "os", "path", "plugin",
    "reflect", "regexp", "runtime", "slices", "sort", "strconv",
    "strings", "structs", "sync", "syscall", "testing", "time",
    "unicode", "unique", "unsafe", "weak",
];

/// Go `isStdPkg`.
pub(super) fn is_std_pkg(path: &str) -> bool {
    STD_PKGS.binary_search(&path).is_ok()
}
