[package]
name = "guff-govet"
description = "Rust port of golang.org/x/tools/go/analysis/passes (go vet)."
keywords = ["go", "govet", "vet", "analysis"]
categories = ["development-tools"]
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "guff_govet"
path = "src/lib.rs"

[dependencies]
guff-ast = { path = "../guff-ast" }
memchr = "2"
guff-analysis = { path = "../guff-analysis" }
guff-constant = { path = "../guff-constant" }
guff-types = { path = "../guff-types" }

[dev-dependencies]
guff-packages = { path = "../guff-packages" }
guff-runner = { path = "../guff-runner" }
guff-types = { path = "../guff-types" }
