// Command goquote emits ground truth for guff's port of strconv.Quote and the
// unicode.IsPrint predicate behind it (crates/guff-staticcheck/src/gostd/strconv.rs).
//
// Output is two sections:
//
//	print<TAB><lo hex><TAB><hi hex>   one row per maximal run of printable runes
//	quote<TAB><hex of input UTF-8><TAB><strconv.Quote output>
//
// The print section lets the Rust side check IsPrint for every rune in the
// whole space against Go's answer, in a few hundred rows instead of a million.
//
// Regenerate with ../regen.sh; never hand-edit the output.
package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"runtime"
	"strconv"
	"unicode/utf8"
)

func printRanges(w *bufio.Writer) {
	lo := rune(-1)
	emit := func(hi rune) {
		if lo >= 0 {
			fmt.Fprintf(w, "print\t%x\t%x\n", lo, hi)
			lo = -1
		}
	}
	for r := rune(0); r <= utf8.MaxRune; r++ {
		// Surrogates are not scalar values; Rust has no char for them.
		if strconv.IsPrint(r) && !(r >= 0xD800 && r <= 0xDFFF) {
			if lo < 0 {
				lo = r
			}
		} else {
			emit(r - 1)
		}
	}
	emit(utf8.MaxRune)
}

// quoteCorpus covers the escape branches: the named escapes, \x for control
// bytes, \u and \U for non-printable runes, the two always-backslashed
// characters, and printable non-ASCII that must survive verbatim.
//
// Every non-ASCII entry is written as an escape — a literal U+FEFF anywhere but
// the first byte is a compile error in Go source, and the rest are invisible.
var quoteCorpus = []string{
	"", ":", "https://golang.org", "a\"b", "a\\b", "a\tb\nc\rd",
	"\a\b\f\v", "\x00", "\x1f", "\x7f", "'", "`",
	"\u00a0", "\u00ff", "\u0301", "\u00ad", "\ufeff", "\u3000", "\u202e",
	"\u65e5\u672c", "\U0001F600", "\U000e0001", "\U0010FFFF",
	"http://[::1]:8080/", "?#[]@!$&'()*+,;=",
	"%zz", "%2", "sc heme://host",
}

// emitRustTable writes the printable ranges as a Rust source file. IsPrint
// cannot be derived from a Unicode-category crate: Go pins its own tables to
// one Unicode version, and any crate on a different version disagrees on every
// code point assigned in between (5812 of them, between Go 1.26 and
// unicode-general-category 1.x). Go's own strconv keeps a generated table for
// exactly this reason, so guff keeps a copy of Go's.
func emitRustTable(w *bufio.Writer) {
	fmt.Fprintln(w, "//! Generated by `compat/oracles/regen.sh goquote-table`; do not edit.")
	fmt.Fprintln(w, "//!")
	fmt.Fprintf(w, "//! Printable-rune ranges of `strconv.IsPrint` as of %s. Regenerating\n", runtimeVersion())
	fmt.Fprintln(w, "//! under a Go release that bumps Unicode will move these ranges — that is a")
	fmt.Fprintln(w, "//! real behaviour change in every `%q` guff renders, so read the diff.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "/// Inclusive `(lo, hi)` pairs, ascending and non-overlapping.")
	fmt.Fprintln(w, "pub(super) const PRINT_RANGES: &[(u32, u32)] = &[")
	lo := rune(-1)
	emit := func(hi rune) {
		if lo >= 0 {
			fmt.Fprintf(w, "    (0x%X, 0x%X),\n", lo, hi)
			lo = -1
		}
	}
	for r := rune(0); r <= utf8.MaxRune; r++ {
		if strconv.IsPrint(r) && !(r >= 0xD800 && r <= 0xDFFF) {
			if lo < 0 {
				lo = r
			}
		} else {
			emit(r - 1)
		}
	}
	emit(utf8.MaxRune)
	fmt.Fprintln(w, "];")
}

func runtimeVersion() string {
	return runtime.Version()
}

func main() {
	rustTable := flag.Bool("rust", false, "emit the printable ranges as a Rust source file")
	flag.Parse()

	w := bufio.NewWriter(os.Stdout)
	defer w.Flush()
	if *rustTable {
		emitRustTable(w)
		return
	}
	printRanges(w)
	for _, s := range quoteCorpus {
		fmt.Fprintf(w, "quote\t%x\t%s\n", s, strconv.Quote(s))
	}
}
