// This is an autogenerated file; do not edit it by hand.

// Package lax carries a marker that only the lax matcher looks for
// (`autogenerated file`, and `do not edit` in a form that is not the strict
// one-line convention), so `generated: strict` keeps its findings.
package lax

func mkerr() error { return nil }

// Run has one unchecked error.
func Run() {
	mkerr()
}
