//! Generated-file fact analyzer.
//!
//! Port of `honnef.co/go/tools/analysis/facts/generated`.

use std::collections::HashMap;
use std::io::{BufRead, BufReader};
use std::path::Path;
use std::sync::OnceLock;

use crate::analyzer::{AnalysisResult, Analyzer, RunError, RunFn};
use crate::pass::Pass;
use crate::passes::inspect;

/// Known code generators we can detect.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum Generator {
    Unknown = 0,
    Goyacc = 1,
    Cgo = 2,
    Stringer = 3,
    ProtocGenGo = 4,
}

const PREFIX: &[u8] = b"// Code generated ";
const SUFFIX: &[u8] = b" DO NOT EDIT.";
const OLD_CGO: &[u8] = b"// Created by cgo - DO NOT EDIT";

/// Maps absolute file paths to their generator kind.
#[derive(Clone, Default)]
pub struct GeneratedResult {
    pub files: HashMap<String, Generator>,
}

fn is_generated_bytes(src: &[u8]) -> Option<Generator> {
    for line in src.split(|&b| b == b'\n') {
        let line = line.strip_suffix(b"\r").unwrap_or(line);
        if line.starts_with(PREFIX) && line.ends_with(SUFFIX) {
            let start = PREFIX.len();
            let end = line.len().saturating_sub(SUFFIX.len());
            if end <= start {
                return Some(Generator::Unknown);
            }
            let text = std::str::from_utf8(&line[start..end]).ok()?;
            return Some(match text {
                "by goyacc." => Generator::Goyacc,
                "by cmd/cgo;" => Generator::Cgo,
                "by protoc-gen-go." => Generator::ProtocGenGo,
                t if t.starts_with("by \"stringer ") => Generator::Stringer,
                t if t.starts_with("by goyacc ") => Generator::Goyacc,
                _ => Generator::Unknown,
            });
        }
        if line == OLD_CGO {
            return Some(Generator::Cgo);
        }
    }
    None
}

fn is_generated(path: &Path) -> Option<Generator> {
    let f = std::fs::File::open(path).ok()?;
    let mut br = BufReader::new(f);
    loop {
        let mut line = Vec::new();
        let n = br.read_until(b'\n', &mut line).ok()?;
        if line.ends_with(b"\r\n") {
            line.truncate(line.len() - 2);
        } else if line.ends_with(b"\n") {
            line.truncate(line.len() - 1);
        }
        if line.starts_with(PREFIX) && line.ends_with(SUFFIX) {
            let start = PREFIX.len();
            let end = line.len().saturating_sub(SUFFIX.len());
            if end <= start {
                return Some(Generator::Unknown);
            }
            let text = std::str::from_utf8(&line[start..end]).ok()?;
            return Some(match text {
                "by goyacc." => Generator::Goyacc,
                "by cmd/cgo;" => Generator::Cgo,
                "by protoc-gen-go." => Generator::ProtocGenGo,
                t if t.starts_with("by \"stringer ") => Generator::Stringer,
                t if t.starts_with("by goyacc ") => Generator::Goyacc,
                _ => Generator::Unknown,
            });
        }
        if line == OLD_CGO {
            return Some(Generator::Cgo);
        }
        if n == 0 {
            break;
        }
    }
    None
}

fn run(pass: &mut Pass<'_>) -> Result<Option<AnalysisResult>, RunError> {
    let _ = pass
        .result_of::<inspect::InspectResult>(inspect::analyzer())
        .ok_or_else(|| "generated requires inspect analyzer".to_string())?;

    let mut result = GeneratedResult::default();
    for (i, _file) in pass.files().iter().enumerate() {
        let path = pass
            .pkg()
            .compiled_go_files
            .get(i)
            .map(|p| p.as_path())
            .filter(|p| p.is_file());
        let Some(path) = path else {
            continue;
        };
        let gen = if let Some(bytes) = pass.pkg().source_bytes(i) {
            is_generated_bytes(bytes)
        } else {
            is_generated(path)
        };
        if let Some(gen) = gen {
            result
                .files
                .insert(path.to_string_lossy().into_owned(), gen);
        }
    }
    Ok(Some(Box::new(result)))
}

fn generated_analyzer_impl() -> Analyzer {
    Analyzer {
        name: "isgenerated",
        doc: "annotate file names that have been code generated",
        url: "https://staticcheck.dev/docs/checks/",
        run: run as RunFn,
        run_despite_errors: true,
        requires: vec![inspect::analyzer()],
        fact_types: vec![],
    }
}

/// The `isgenerated` analyzer singleton.
pub fn analyzer() -> &'static Analyzer {
    static A: OnceLock<Analyzer> = OnceLock::new();
    A.get_or_init(generated_analyzer_impl)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    #[test]
    fn detects_generated_header() {
        let dir = std::env::temp_dir().join(format!("guff-gen-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("gen.go");
        let mut f = std::fs::File::create(&path).unwrap();
        writeln!(f, "// Code generated by protoc-gen-go. DO NOT EDIT.").unwrap();
        writeln!(f, "package p").unwrap();
        assert_eq!(is_generated(&path), Some(Generator::ProtocGenGo));
        let _ = std::fs::remove_dir_all(&dir);
    }
}
