//! Generated-file detection for `formatters.exclusions.generated`
//! (golangci-lint `GeneratedFileFilter` / `lax` · `strict` · `disable`).

/// How to treat generated Go sources when formatting.
///
/// Matches golangci-lint `formatters.exclusions.generated` (default: [`Lax`](Self::Lax)).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum GeneratedMode {
    /// Skip files whose leading comments contain common generator markers
    /// (`code generated`, `do not edit`, `autogenerated file`, swagger codegen).
    #[default]
    Lax,
    /// Skip only files with a line matching
    /// `^// Code generated .* DO NOT EDIT\.$` before the package clause
    /// (<https://go.dev/s/generatedcode>).
    Strict,
    /// Never skip on generated-file heuristics.
    Disable,
}

impl GeneratedMode {
    /// Parse a golangci mode string (`lax` / `strict` / `disable`).
    /// Unknown or empty → [`Lax`](Self::Lax) (formatter default).
    pub fn parse(s: Option<&str>) -> Self {
        match s.map(str::trim).filter(|s| !s.is_empty()) {
            None => Self::Lax,
            Some(s) if s.eq_ignore_ascii_case("lax") => Self::Lax,
            Some(s) if s.eq_ignore_ascii_case("strict") => Self::Strict,
            Some(s) if s.eq_ignore_ascii_case("disable") => Self::Disable,
            Some(_) => Self::Lax,
        }
    }
}

/// Returns true when `src` should be skipped under `mode`.
pub fn is_generated(src: &[u8], mode: GeneratedMode) -> bool {
    let src = strip_bom(src);
    match mode {
        GeneratedMode::Disable => false,
        GeneratedMode::Strict => is_generated_strict(src),
        GeneratedMode::Lax => is_generated_lax(src),
    }
}

/// A UTF-8 byte order mark at the very start of the file, which upstream never
/// sees: golangci-lint reads comments through `parser.ParseFile`, and
/// `go/scanner.Init` does
///
/// ```go
/// s.next()
/// if s.ch == bom { s.next() } // ignore BOM at file beginning
/// ```
///
/// Our scan is a line scanner, and `str::trim` does not remove U+FEFF — Rust's
/// `White_Space` property does not include it. So without this the very first
/// line reads as neither a comment nor a package clause, the scan stops there,
/// and a generated file whose first byte is a BOM is never recognised as one.
/// cilium/ebpf's `asm/func_lin.go` is that file, and it is the whole of the
/// `ebpf` corpus target's guff-only finding.
fn strip_bom(src: &[u8]) -> &[u8] {
    src.strip_prefix(&[0xef, 0xbb, 0xbf][..]).unwrap_or(src)
}

/// Lax markers (lowercase), matching golangci `exclusion_generated_file_filter.go`.
const LAX_MARKERS: &[&str] = &[
    "code generated",
    "do not edit",
    "autogenerated file",
    // Swagger Codegen header fragment (includes leading `* ` from the block comment body).
    "* generated by: swagger codegen ",
];

fn is_generated_lax(src: &[u8]) -> bool {
    let doc = leading_comment_doc(src).to_ascii_lowercase();
    LAX_MARKERS.iter().any(|m| doc.contains(m))
}

/// Line matches `^// Code generated .* DO NOT EDIT\.$`.
fn line_is_strict_generated(line: &str) -> bool {
    let line = line.trim_end_matches(['\r']);
    line.starts_with("// Code generated ") && line.ends_with(" DO NOT EDIT.")
}

fn is_generated_strict(src: &[u8]) -> bool {
    let s = String::from_utf8_lossy(src);
    let mut in_block = false;
    for raw in s.lines() {
        let line = raw.trim_end_matches(['\r']);
        let trimmed = line.trim();
        if in_block {
            if trimmed.contains("*/") {
                in_block = false;
            }
            continue;
        }
        if trimmed.is_empty() {
            continue;
        }
        // Strict mode only matches `//` line comments (Go generatedcode convention).
        if trimmed.starts_with("//") {
            if line_is_strict_generated(trimmed) {
                return true;
            }
            continue;
        }
        if trimmed.starts_with("/*") {
            if !trimmed.contains("*/") {
                in_block = true;
            }
            continue;
        }
        // First non-comment, non-blank text → stop.
        break;
    }
    false
}

/// Collect the comment text golangci's `getComments` sees, i.e. every comment
/// group `parser.ParseFile(…, PackageClauseOnly|ParseComments)` collected.
///
/// That is **not** "the comments before the package clause". The parser reads
/// one token past the clause, and its `next()` consumes comment groups until
/// the first non-comment token — so the groups written directly below
/// `package p` are collected as well, however many of them there are and
/// whatever blank lines separate them. Scanning only the leading comments made
/// guff report a file upstream treats as generated (`generated-lax`'s
/// after/after.go).
///
/// Directive comments (`//go:generate`, `//line`, …) are dropped, because
/// `ast.CommentGroup.Text` drops them: a marker inside one is invisible to the
/// matcher.
fn leading_comment_doc(src: &[u8]) -> String {
    let s = String::from_utf8_lossy(src);
    let mut out = String::new();
    let mut in_block = false;
    let mut block_buf = String::new();
    let mut past_package = false;

    for raw in s.lines() {
        let line = raw.trim_end_matches(['\r']);
        if in_block {
            block_buf.push('\n');
            block_buf.push_str(line);
            if line.contains("*/") {
                in_block = false;
                append_block_comment_text(&mut out, &block_buf);
                block_buf.clear();
            }
            continue;
        }

        let trimmed = line.trim();
        if trimmed.is_empty() {
            continue;
        }
        if let Some(rest) = trimmed.strip_prefix("//") {
            if is_directive(rest) {
                continue;
            }
            if !out.is_empty() {
                out.push('\n');
            }
            out.push_str(rest.trim());
            continue;
        }
        if trimmed.starts_with("/*") {
            if trimmed.contains("*/") {
                append_block_comment_text(&mut out, trimmed);
            } else {
                in_block = true;
                block_buf = trimmed.to_string();
            }
            continue;
        }
        // The package clause is the one non-comment line that does not end the
        // scan: the parser is still one token short of stopping.
        if !past_package && is_package_clause(trimmed) {
            past_package = true;
            continue;
        }
        // Any other code: the parser has its token and collects no more.
        break;
    }
    out
}

/// `package p` (optionally with a trailing comment), as the line that lets the
/// scan continue.
fn is_package_clause(trimmed: &str) -> bool {
    trimmed
        .strip_prefix("package")
        .is_some_and(|rest| rest.starts_with([' ', '\t']))
}

/// go/ast `isDirective`, on a `//` comment's text (the `//` already stripped).
///
/// A directive is `//line `, `//extern `, `//export `, or `//name:value` where
/// `name` is lowercase alphanumerics — and never a comment that starts with a
/// space, which is why `// go:generate` is ordinary text.
fn is_directive(c: &str) -> bool {
    if c.starts_with("line ") || c.starts_with("extern ") || c.starts_with("export ") {
        return true;
    }
    if c.starts_with(' ') {
        return false;
    }
    let bytes = c.as_bytes();
    let Some(colon) = bytes.iter().position(|b| *b == b':') else {
        return false;
    };
    if colon == 0 || colon + 1 >= bytes.len() {
        return false;
    }
    (0..=colon + 1).all(|i| {
        i == colon || bytes[i].is_ascii_lowercase() || bytes[i].is_ascii_digit()
    })
}

fn append_block_comment_text(out: &mut String, block: &str) {
    let mut body = block.trim();
    if let Some(r) = body.strip_prefix("/*") {
        body = r;
    }
    if let Some(r) = body.strip_suffix("*/") {
        body = r;
    }
    let text = body.trim();
    if text.is_empty() {
        return;
    }
    if !out.is_empty() {
        out.push('\n');
    }
    out.push_str(text);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_modes() {
        assert_eq!(GeneratedMode::parse(None), GeneratedMode::Lax);
        assert_eq!(GeneratedMode::parse(Some("lax")), GeneratedMode::Lax);
        assert_eq!(GeneratedMode::parse(Some("STRICT")), GeneratedMode::Strict);
        assert_eq!(GeneratedMode::parse(Some("disable")), GeneratedMode::Disable);
        assert_eq!(GeneratedMode::parse(Some("wat")), GeneratedMode::Lax);
    }

    /// A UTF-8 BOM before the marker, which is what cilium/ebpf's
    /// `asm/func_lin.go` looks like. Upstream reads comments through
    /// `parser.ParseFile`, and `go/scanner.Init` ignores a BOM at the start of
    /// the file, so every one of these is generated there. Rust's `str::trim`
    /// does not remove U+FEFF, so before [`strip_bom`] the scan died on line 1
    /// and every one of these came back `false`.
    #[test]
    fn a_leading_bom_does_not_hide_the_marker() {
        let bom = "\u{feff}";
        let cases: &[(&str, GeneratedMode, bool)] = &[
            // The exact ebpf shape: BOM + `//` marker.
            (
                "// Code generated by tool. DO NOT EDIT.\n\npackage p\n",
                GeneratedMode::Strict,
                true,
            ),
            // A build directive between the BOM and the marker.
            (
                "//go:build !ignore\n\n// Code generated by tool. DO NOT EDIT.\n\npackage p\n",
                GeneratedMode::Strict,
                true,
            ),
            // Lax sees it too.
            (
                "// AUTOGENERATED FILE: easyjson file.go\npackage p\n",
                GeneratedMode::Lax,
                true,
            ),
            // A block comment is a lax marker only — strict wants `//`.
            (
                "/*\n * Code generated by tool. DO NOT EDIT.\n */\n\npackage p\n",
                GeneratedMode::Lax,
                true,
            ),
            (
                "/*\n * Code generated by tool. DO NOT EDIT.\n */\n\npackage p\n",
                GeneratedMode::Strict,
                false,
            ),
            // A BOM must not turn a non-generated file into a generated one.
            ("// just a comment\n\npackage p\n", GeneratedMode::Strict, false),
            ("// just a comment\n\npackage p\n", GeneratedMode::Lax, false),
        ];
        for (body, mode, want) in cases {
            let with_bom = format!("{bom}{body}");
            assert_eq!(
                is_generated(with_bom.as_bytes(), *mode),
                *want,
                "with BOM, {mode:?}: {body:?}"
            );
            // The BOM must change nothing: same answer without it.
            assert_eq!(
                is_generated(body.as_bytes(), *mode),
                *want,
                "without BOM, {mode:?}: {body:?}"
            );
        }
    }

    #[test]
    fn a_bom_alone_is_not_a_marker() {
        // Only a *leading* BOM is skipped; one in the middle is ordinary text
        // and must not be mistaken for anything.
        assert!(!is_generated("\u{feff}package p\n".as_bytes(), GeneratedMode::Lax));
        assert!(!is_generated(
            "// a\u{feff}b\npackage p\n".as_bytes(),
            GeneratedMode::Lax
        ));
    }

    #[test]
    fn disable_never_skips() {
        let src = b"// Code generated by tool. DO NOT EDIT.\npackage p\n";
        assert!(!is_generated(src, GeneratedMode::Disable));
    }

    #[test]
    fn strict_matches_go_convention() {
        let ok = b"// Code generated by tool. DO NOT EDIT.\npackage p\n";
        assert!(is_generated(ok, GeneratedMode::Strict));
        let bad = b"// Code generated by tool. DO NOT EDIT\npackage p\n"; // missing trailing .
        assert!(!is_generated(bad, GeneratedMode::Strict));
        let lax_only = b"// DO NOT EDIT\npackage p\n";
        assert!(!is_generated(lax_only, GeneratedMode::Strict));
        assert!(is_generated(lax_only, GeneratedMode::Lax));
    }

    #[test]
    fn lax_matches_common_markers() {
        let samples: &[&[u8]] = &[
            b"// generated by stringer -type Pill; DO NOT EDIT\npackage p\n",
            b"// AUTOGENERATED FILE: easyjson file.go\npackage p\n",
            b"/* Created by cgo - DO NOT EDIT. */\npackage p\n",
            b"// * Generated by: Swagger Codegen (https://example.com)\npackage p\n",
        ];
        for src in samples {
            assert!(
                is_generated(src, GeneratedMode::Lax),
                "expected lax match for {}",
                String::from_utf8_lossy(src)
            );
        }
        assert!(!is_generated(
            b"// code not generated by\npackage p\n",
            GeneratedMode::Lax
        ));
        assert!(!is_generated(b"package p\n", GeneratedMode::Lax));
    }

    #[test]
    fn strict_ignores_comments_after_package() {
        let src = b"package p\n// Code generated by tool. DO NOT EDIT.\n";
        assert!(!is_generated(src, GeneratedMode::Strict));
    }

    #[test]
    fn lax_sees_the_comment_groups_below_the_package_clause() {
        // `PackageClauseOnly` does not mean "stop at the package clause": the
        // parser reads one token further, collecting every comment group up to
        // it. Measured against go/parser, not assumed.
        let src = b"package p\n\n// Code generated by tool. DO NOT EDIT.\n\nfunc F() {}\n";
        assert!(is_generated(src, GeneratedMode::Lax));
        assert!(!is_generated(src, GeneratedMode::Strict));

        // Several groups, blank lines between them: all collected.
        let two = b"package p\n\n// one\n\n// autogenerated file\n\nfunc F() {}\n";
        assert!(is_generated(two, GeneratedMode::Lax));

        // The first non-comment token after the clause ends the scan.
        let after_import = b"package p\n\nimport \"fmt\"\n\n// Code generated by tool. DO NOT EDIT.\nfunc F() { fmt.Print() }\n";
        assert!(!is_generated(after_import, GeneratedMode::Lax));
    }

    #[test]
    fn lax_skips_directive_comments() {
        // `ast.CommentGroup.Text` drops `//name:value` lines, so a marker in
        // one is invisible — but `// go:...`, with a space, is ordinary text.
        assert!(!is_generated(
            b"//tool:do not edit\npackage p\n",
            GeneratedMode::Lax
        ));
        assert!(is_generated(
            b"// tool:do not edit\npackage p\n",
            GeneratedMode::Lax
        ));
        assert!(!is_generated(
            b"//line do not edit\npackage p\n",
            GeneratedMode::Lax
        ));
    }
}
