//! Generated-file detection for `formatters.exclusions.generated`
//! (golangci-lint `GeneratedFileFilter` / `lax` · `strict` · `disable`).

/// How to treat generated Go sources when formatting.
///
/// Matches golangci-lint `formatters.exclusions.generated` (default: [`Lax`](Self::Lax)).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum GeneratedMode {
    /// Skip files whose leading comments contain common generator markers
    /// (`code generated`, `do not edit`, `autogenerated file`, swagger codegen).
    #[default]
    Lax,
    /// Skip only files with a line matching
    /// `^// Code generated .* DO NOT EDIT\.$` before the package clause
    /// (<https://go.dev/s/generatedcode>).
    Strict,
    /// Never skip on generated-file heuristics.
    Disable,
}

impl GeneratedMode {
    /// Parse a golangci mode string (`lax` / `strict` / `disable`).
    /// Unknown or empty → [`Lax`](Self::Lax) (formatter default).
    pub fn parse(s: Option<&str>) -> Self {
        match s.map(str::trim).filter(|s| !s.is_empty()) {
            None => Self::Lax,
            Some(s) if s.eq_ignore_ascii_case("lax") => Self::Lax,
            Some(s) if s.eq_ignore_ascii_case("strict") => Self::Strict,
            Some(s) if s.eq_ignore_ascii_case("disable") => Self::Disable,
            Some(_) => Self::Lax,
        }
    }
}

/// Returns true when `src` should be skipped under `mode`.
pub fn is_generated(src: &[u8], mode: GeneratedMode) -> bool {
    match mode {
        GeneratedMode::Disable => false,
        GeneratedMode::Strict => is_generated_strict(src),
        GeneratedMode::Lax => is_generated_lax(src),
    }
}

/// Lax markers (lowercase), matching golangci `exclusion_generated_file_filter.go`.
const LAX_MARKERS: &[&str] = &[
    "code generated",
    "do not edit",
    "autogenerated file",
    // Swagger Codegen header fragment (includes leading `* ` from the block comment body).
    "* generated by: swagger codegen ",
];

fn is_generated_lax(src: &[u8]) -> bool {
    let doc = leading_comment_doc(src).to_ascii_lowercase();
    LAX_MARKERS.iter().any(|m| doc.contains(m))
}

/// Line matches `^// Code generated .* DO NOT EDIT\.$`.
fn line_is_strict_generated(line: &str) -> bool {
    let line = line.trim_end_matches(['\r']);
    line.starts_with("// Code generated ") && line.ends_with(" DO NOT EDIT.")
}

fn is_generated_strict(src: &[u8]) -> bool {
    let s = String::from_utf8_lossy(src);
    let mut in_block = false;
    for raw in s.lines() {
        let line = raw.trim_end_matches(['\r']);
        let trimmed = line.trim();
        if in_block {
            if trimmed.contains("*/") {
                in_block = false;
            }
            continue;
        }
        if trimmed.is_empty() {
            continue;
        }
        // Strict mode only matches `//` line comments (Go generatedcode convention).
        if trimmed.starts_with("//") {
            if line_is_strict_generated(trimmed) {
                return true;
            }
            continue;
        }
        if trimmed.starts_with("/*") {
            if !trimmed.contains("*/") {
                in_block = true;
            }
            continue;
        }
        // First non-comment, non-blank text → stop.
        break;
    }
    false
}

/// Collect leading comment text (before first non-comment code), approximating
/// golangci `getComments` with `PackageClauseOnly|ParseComments`.
fn leading_comment_doc(src: &[u8]) -> String {
    let s = String::from_utf8_lossy(src);
    let mut out = String::new();
    let mut in_block = false;
    let mut block_buf = String::new();

    for raw in s.lines() {
        let line = raw.trim_end_matches(['\r']);
        if in_block {
            block_buf.push('\n');
            block_buf.push_str(line);
            if line.contains("*/") {
                in_block = false;
                append_block_comment_text(&mut out, &block_buf);
                block_buf.clear();
            }
            continue;
        }

        let trimmed = line.trim();
        if trimmed.is_empty() {
            continue;
        }
        if let Some(rest) = trimmed.strip_prefix("//") {
            if !out.is_empty() {
                out.push('\n');
            }
            out.push_str(rest.trim());
            continue;
        }
        if trimmed.starts_with("/*") {
            if trimmed.contains("*/") {
                append_block_comment_text(&mut out, trimmed);
            } else {
                in_block = true;
                block_buf = trimmed.to_string();
            }
            continue;
        }
        // Hit package / code.
        break;
    }
    out
}

fn append_block_comment_text(out: &mut String, block: &str) {
    let mut body = block.trim();
    if let Some(r) = body.strip_prefix("/*") {
        body = r;
    }
    if let Some(r) = body.strip_suffix("*/") {
        body = r;
    }
    let text = body.trim();
    if text.is_empty() {
        return;
    }
    if !out.is_empty() {
        out.push('\n');
    }
    out.push_str(text);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_modes() {
        assert_eq!(GeneratedMode::parse(None), GeneratedMode::Lax);
        assert_eq!(GeneratedMode::parse(Some("lax")), GeneratedMode::Lax);
        assert_eq!(GeneratedMode::parse(Some("STRICT")), GeneratedMode::Strict);
        assert_eq!(GeneratedMode::parse(Some("disable")), GeneratedMode::Disable);
        assert_eq!(GeneratedMode::parse(Some("wat")), GeneratedMode::Lax);
    }

    #[test]
    fn disable_never_skips() {
        let src = b"// Code generated by tool. DO NOT EDIT.\npackage p\n";
        assert!(!is_generated(src, GeneratedMode::Disable));
    }

    #[test]
    fn strict_matches_go_convention() {
        let ok = b"// Code generated by tool. DO NOT EDIT.\npackage p\n";
        assert!(is_generated(ok, GeneratedMode::Strict));
        let bad = b"// Code generated by tool. DO NOT EDIT\npackage p\n"; // missing trailing .
        assert!(!is_generated(bad, GeneratedMode::Strict));
        let lax_only = b"// DO NOT EDIT\npackage p\n";
        assert!(!is_generated(lax_only, GeneratedMode::Strict));
        assert!(is_generated(lax_only, GeneratedMode::Lax));
    }

    #[test]
    fn lax_matches_common_markers() {
        let samples: &[&[u8]] = &[
            b"// generated by stringer -type Pill; DO NOT EDIT\npackage p\n",
            b"// AUTOGENERATED FILE: easyjson file.go\npackage p\n",
            b"/* Created by cgo - DO NOT EDIT. */\npackage p\n",
            b"// * Generated by: Swagger Codegen (https://example.com)\npackage p\n",
        ];
        for src in samples {
            assert!(
                is_generated(src, GeneratedMode::Lax),
                "expected lax match for {}",
                String::from_utf8_lossy(src)
            );
        }
        assert!(!is_generated(
            b"// code not generated by\npackage p\n",
            GeneratedMode::Lax
        ));
        assert!(!is_generated(b"package p\n", GeneratedMode::Lax));
    }

    #[test]
    fn strict_ignores_comments_after_package() {
        let src = b"package p\n// Code generated by tool. DO NOT EDIT.\n";
        assert!(!is_generated(src, GeneratedMode::Strict));
    }
}
