#!/usr/bin/env python3
"""Rewrite a target's golangci config to enable **every** linter (Phase 2).

The OSS tier runs each checkout's real config, and those configs are modest:
across all eight targets only seven linters ever fire (errcheck, gosec, govet,
ineffassign, modernize, staticcheck, unused). The other 107 are compared
exclusively against hand-written isolate fixtures averaging eleven lines each.

This produces the same eight repositories with ``linters.default: all``, so
every linter meets real code — the shapes a fixture author would never think
to write. See docs/COMPAT-HARDENING.md Phase 2.

What is kept from the target's own config, and why:

``run``
    Build tags, ``tests``, ``go`` version and skip-dirs decide which files
    exist at all. Changing them would turn a linter difference into a file-set
    difference, which is Phase 1's job (compat/filesets.sh), not this one.

``linters.exclusions``
    Applied identically to both tools, so keeping them cannot mask a
    divergence — it only narrows the compared surface. They stay because a
    repo's exclusions are usually what keeps generated code out, and without
    them the run drowns in findings from protobuf and deepcopy files that
    neither tool's users ever see.

``linters.settings``
    Same reasoning: both tools read the same settings. A linter the repo never
    enabled simply has no entry and both tools fall back to the same defaults.

What is dropped:

``linters.enable`` / ``linters.disable``
    Replaced wholesale by ``default: all`` — the entire point.

``formatters`` / ``severity``
    Formatters are compared by the golden tier and would swamp this diff;
    ``severity`` rewrites severities without changing the finding set.

Usage:
  python3 compat/all_linters.py --source .golangci.yml -o out.yml
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from filesets import load_lenient  # noqa: E402

try:
    import yaml
except ImportError:  # pragma: no cover
    yaml = None  # type: ignore


def build_config(source: dict | None) -> dict:
    cfg = dict(source or {})
    cfg["version"] = "2"

    src_linters = dict(cfg.get("linters") or {})
    linters: dict = {"default": "all"}
    for key in ("exclusions", "settings"):
        if src_linters.get(key) is not None:
            linters[key] = src_linters[key]
    cfg["linters"] = linters

    issues = dict(cfg.get("issues") or {})
    # Identical-message truncation would rotate which findings survive on each
    # side independently, so a stable diff needs the caps off.
    issues.update({"max-issues-per-linter": 0, "max-same-issues": 0})
    cfg["issues"] = issues

    run = dict(cfg.get("run") or {})
    run.setdefault("tests", True)
    cfg["run"] = run

    cfg.pop("formatters", None)
    cfg.pop("severity", None)
    return cfg


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--source", default=None, help="Target's own .golangci.yml")
    ap.add_argument("-o", "--output", required=True)
    args = ap.parse_args(argv)

    if yaml is None:
        raise SystemExit("PyYAML required for compat/all_linters.py")

    source = None
    if args.source and Path(args.source).is_file():
        source = load_lenient(Path(args.source))

    text = yaml.safe_dump(build_config(source), default_flow_style=False, sort_keys=False)
    Path(args.output).write_text(
        "# Generated by compat/all_linters.py — Phase 2 `default: all` tier.\n"
        "# Not the repo's real config: every linter is enabled on purpose.\n" + text,
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
