#!/usr/bin/env python3
"""Compare which `.go` files guff and golangci-lint actually analyzed (Phase 1c).

Build tags, `run.tests`, vendor, generated-file handling and package-pattern
expansion all decide the *input* to every linter. When the two tools disagree
there, it surfaces only as a finding diff somewhere else entirely — and not at
all when the files they disagree about happen to be clean. So compare the input
directly.

Neither tool will list its analyzed files, so we make them tell us: run both
with a config whose only linter is `goheader` and whose template cannot match.
goheader reports **once per analyzed file**, so the set of files appearing in
the output *is* the set of files analyzed.

The probe config keeps the target's own `run:` block and `linters.exclusions`
(build tags, tests, vendor and generated rules are exactly what is under test)
and replaces only the enable-set.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from normalize import load_issues, normalize_path  # noqa: E402

try:
    import yaml
except ImportError:  # pragma: no cover
    yaml = None  # type: ignore

# Any template that cannot occur in real source. goheader then reports on every
# file it was given, which is the whole point.
PROBE_TEMPLATE = "GUFF-FILESET-PROBE-NEVER-MATCHES"


def load_lenient(path: Path) -> dict | None:
    """Parse a target's own config, tolerating what Go's YAML accepts.

    golangci-lint reads these with gopkg.in/yaml, which is happy with trailing
    tabs; PyYAML is not (kubernetes' `hack/golangci.yaml` has `gocritic:\\t`).
    Trailing whitespace carries no meaning in a lint config, so strip it and
    retry. If it still will not parse, say so and fall back to defaults — both
    tools get the same generated probe either way, so the comparison stays
    valid; it just stops exercising that repo's own `run:` block.
    """
    text = path.read_text(encoding="utf-8")
    for attempt in (text, "\n".join(line.rstrip() for line in text.splitlines())):
        try:
            data = yaml.safe_load(attempt)
        except yaml.YAMLError:
            continue
        if isinstance(data, dict):
            return data
        return None
    print(f"  warning: {path} did not parse; probing with default run settings", file=sys.stderr)
    return None


def build_config(source: dict | None) -> dict:
    cfg = dict(source or {})
    cfg["version"] = "2"

    linters = dict(cfg.get("linters") or {})
    # Keep exclusions: whether a file is excluded is part of "was it analyzed".
    exclusions = linters.get("exclusions")
    linters = {
        "default": "none",
        "enable": ["goheader"],
        "settings": {"goheader": {"template": PROBE_TEMPLATE}},
    }
    if exclusions is not None:
        linters["exclusions"] = exclusions
    cfg["linters"] = linters

    issues = dict(cfg.get("issues") or {})
    # One finding per file is the signal; caps and uniq-by-line would eat it.
    issues.update({"max-issues-per-linter": 0, "max-same-issues": 0, "uniq-by-line": False})
    cfg["issues"] = issues

    run = dict(cfg.get("run") or {})
    run.setdefault("tests", True)
    cfg["run"] = run

    # Formatters would add findings that are not one-per-file.
    cfg.pop("formatters", None)
    cfg.pop("severity", None)
    return cfg


def file_set(json_path: str, root: str) -> set[str]:
    return {normalize_path(i["Pos"]["Filename"], root) for i in load_issues(json_path)}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    sub = ap.add_subparsers(dest="cmd", required=True)

    p_cfg = sub.add_parser("config", help="Emit the probe config for a target")
    p_cfg.add_argument("--source", default=None, help="Target's own .golangci.yml")
    p_cfg.add_argument("-o", "--output", required=True)

    p_diff = sub.add_parser("diff", help="Diff the two tools' analyzed file sets")
    p_diff.add_argument("--target", required=True)
    p_diff.add_argument("--root", required=True)
    p_diff.add_argument("--guff", required=True)
    p_diff.add_argument("--golangci", required=True)

    args = ap.parse_args(argv)

    if args.cmd == "config":
        if yaml is None:
            raise SystemExit("PyYAML required for compat/filesets.py")
        source = None
        if args.source and Path(args.source).is_file():
            source = load_lenient(Path(args.source))
        text = yaml.safe_dump(build_config(source), default_flow_style=False, sort_keys=False)
        Path(args.output).write_text(
            "# Generated by compat/filesets.py — file-set probe, not a real lint config.\n" + text,
            encoding="utf-8",
        )
        return 0

    g = file_set(args.guff, args.root)
    c = file_set(args.golangci, args.root)
    only_guff = sorted(g - c)
    only_gcl = sorted(c - g)

    print(
        f"  {args.target}: guff={len(g)} golangci={len(c)} shared={len(g & c)} "
        f"guff-only={len(only_guff)} golangci-only={len(only_gcl)}"
        + ("" if not (only_guff or only_gcl) else "  [MISMATCH]")
    )
    if not g and not c:
        # Both empty means the probe never fired — a broken probe would
        # otherwise report a perfect match forever.
        print(f"  {args.target}: probe produced no findings at all", file=sys.stderr)
        return 1
    for f in only_guff[:20]:
        print(f"    +guff  {f}")
    for f in only_gcl[:20]:
        print(f"    +gcl   {f}")
    extra = len(only_guff) + len(only_gcl) - min(20, len(only_guff)) - min(20, len(only_gcl))
    if extra > 0:
        print(f"    … and {extra} more")
    return 1 if (only_guff or only_gcl) else 0


if __name__ == "__main__":
    raise SystemExit(main())
