#!/usr/bin/env python3
"""Strict golden comparison for the check-level compat gate (Phase 3).

Unlike ``compat/normalize.py``, this module does **no** message normalization
and compares **column and severity** as well:

    key = path:line:col:linter:severity:text

``normalize.py`` exists to make two tools' *finding sets* collide across known
phrasing differences; that is the right trade for the OSS tier, where the goal
is "did we miss a finding". The golden tier asks a stricter question — "is the
rendered diagnostic byte-identical to golangci-lint's" — so every difference
that a user would see in their terminal must show up here, including the ones
``normalize_message`` deliberately erases (see COMPAT-HARDENING.md §5).

Goldens are generated by running golangci-lint itself (``regen.sh``); nobody
hand-writes an expected value, so no assumption can smuggle itself in.
"""

from __future__ import annotations

import argparse
import collections
import json
import sys
from pathlib import Path
from typing import Iterable

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from normalize import is_related_information, load_issues, normalize_path  # noqa: E402


def escape(text: str) -> str:
    """Make ``text`` safe for a one-key-per-line golden file."""
    return text.replace("\\", "\\\\").replace("\n", "\\n").replace("\r", "\\r")


def issue_key(issue: dict, root: str) -> str:
    pos = issue["Pos"]
    path = normalize_path(pos["Filename"], root)
    return ":".join(
        (
            path,
            str(pos["Line"]),
            str(pos["Column"]),
            issue["FromLinter"],
            issue.get("Severity") or "",
            escape(issue.get("Text") or ""),
        )
    )


def sort_key(key: str) -> tuple:
    """Order a golden by source position, not lexically.

    Splitting from the left is safe: the golden's own paths never contain a
    colon (module-relative POSIX paths), and only the trailing message may.
    """
    path, line, col, rest = key.split(":", 3)
    return (path, int(line), int(col), rest)


def issue_keys(issues: Iterable[dict], root: str) -> list[str]:
    keys = [issue_key(i, root) for i in issues if not is_related_information(i)]
    return sorted(keys, key=sort_key)


HEADER = """\
# Golden finding set — generated, do not hand-edit.
#
# Regenerate with: ./compat/golden/regen.sh {case}
# Produced by running golangci-lint on compat/golden/cases/{case}/.
# key = path:line:col:linter:severity:text  (no normalization; \\n is escaped)
"""


def render_golden(case: str, keys: list[str], tool_version: str) -> str:
    lines = [HEADER.format(case=case), f"# golangci-lint: {tool_version}", "", *keys]
    return "\n".join(lines) + "\n"


def parse_golden(path: Path | str) -> list[str]:
    out: list[str] = []
    for raw in Path(path).read_text(encoding="utf-8").splitlines():
        line = raw.rstrip("\n")
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        out.append(line)
    return out


def confirm(runs: list[list[str]], confirmations: int) -> list[str] | None:
    """Return the key list seen at least `confirmations` times, else None.

    golangci-lint is not a deterministic function of its input. Measured on the
    pinned 2.12.2 against `cases/revive`: 7 of 24 cold-cache runs returned
    between 57 and 287 findings where the complete answer is 288, and the loss
    is a different random subset every time. The cause is upstream and precise
    — see compat/golden/README.md "Upstream is not a function" — but the
    consequence for this harness is what matters: **a golden written from one
    run can be silently truncated, and a truncated golden stops comparing.**
    That is the exact failure §1 of COMPAT-HARDENING.md exists to prevent, so
    the regeneration path refuses to write until it has seen the same answer
    twice.

    Confirmation is deliberately "seen N times", not "union of all runs". A
    union assumes the only failure mode is loss; revive also has a memoization
    race that *moves* a finding between files (see cases/revive/sources.txt),
    and a union would happily record both positions as expected.
    """
    tally: collections.Counter[tuple[str, ...]] = collections.Counter()
    for run in runs:
        tally[tuple(run)] += 1
        if tally[tuple(run)] >= confirmations:
            return run
    return None


def format_unconfirmed(case: str, runs: list[list[str]]) -> str:
    """Explain which keys are unstable across `runs`, largest run as the base."""
    base = max(runs, key=len)
    lines = [
        f"{case}: {len(runs)} run(s) of golangci-lint did not agree "
        f"(sizes {[len(r) for r in runs]})"
    ]
    unstable: set[str] = set()
    for run in runs:
        unstable |= set(base) ^ set(run)
    for k in sorted(unstable, key=sort_key)[:20]:
        seen = sum(1 for r in runs if k in r)
        lines.append(f"  {seen}/{len(runs)} runs {k}")
    if len(unstable) > 20:
        lines.append(f"  ... and {len(unstable) - 20} more")
    return "\n".join(lines)


def diff(expected: list[str], actual: list[str]) -> tuple[list[str], list[str]]:
    """Return (missing, extra) as multisets: golden-only and guff-only keys."""
    exp, act = collections.Counter(expected), collections.Counter(actual)
    missing = sorted((exp - act).elements(), key=sort_key)
    extra = sorted((act - exp).elements(), key=sort_key)
    return missing, extra


def format_diff(case: str, expected: list[str], actual: list[str]) -> str:
    missing, extra = diff(expected, actual)
    n_both = len(expected) - len(missing)
    lines = [
        f"{case}: guff={len(actual)} golden={len(expected)} match={n_both} "
        f"missing={len(missing)} extra={len(extra)}"
    ]
    for k in missing:
        lines.append(f"  -golden {k}")
    for k in extra:
        lines.append(f"  +guff   {k}")
    return "\n".join(lines)


def check_ratchet(case: str, path: str | None, missing: int, extra: int) -> int:
    """Fail unless `path` records a ratchet baseline this run does not exceed.

    A case with a ratchet is one whose remaining diff is real, understood, and
    being worked down — not one whose diff is being tolerated. It is NOT an
    allowlist: nothing is suppressed, every differing finding is still printed,
    and the only thing the file buys is that CI stays red-free while the count
    goes *down*. Growing either count fails, and so does leaving the file in
    place once the case reaches zero.
    """
    if not path or not Path(path).exists():
        return 1
    base = json.loads(Path(path).read_text(encoding="utf-8"))
    b_missing, b_extra = int(base.get("missing", 0)), int(base.get("extra", 0))
    if missing > b_missing or extra > b_extra:
        print(
            f"  {case}: RATCHET EXCEEDED — missing {missing} > {b_missing}"
            f" or extra {extra} > {b_extra}. Fix the regression, or argue the"
            f" new baseline into {path}.",
            file=sys.stderr,
        )
        return 1
    if missing < b_missing or extra < b_extra:
        print(
            f"  {case}: ratchet improved (missing {b_missing}->{missing},"
            f" extra {b_extra}->{extra}) — lower it in {path}."
        )
    else:
        print(f"  {case}: at ratchet baseline (missing {missing}, extra {extra})")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    sub = ap.add_subparsers(dest="cmd", required=True)

    p_write = sub.add_parser("write", help="Write a golden from golangci-lint JSON dumps")
    p_write.add_argument("--case", required=True)
    p_write.add_argument("--root", required=True)
    p_write.add_argument(
        "--golangci",
        action="append",
        required=True,
        metavar="JSON",
        help="A golangci-lint dump; repeat to supply independent runs of the same case",
    )
    p_write.add_argument(
        "--confirmations",
        type=int,
        default=2,
        help="Runs that must produce identical keys before the golden is written",
    )
    p_write.add_argument("--tool-version", default="unknown")
    p_write.add_argument("-o", "--output", required=True)

    p_check = sub.add_parser("check", help="Compare a guff JSON dump against a golden")
    p_check.add_argument("--case", required=True)
    p_check.add_argument("--root", required=True)
    p_check.add_argument("--guff", required=True)
    p_check.add_argument("--golden", required=True)
    p_check.add_argument(
        "--ratchet",
        help="Path to the case's ratchet.json (a case still being brought to zero)",
    )

    args = ap.parse_args(argv)

    if args.cmd == "write":
        runs = [issue_keys(load_issues(p), args.root) for p in args.golangci]
        keys = confirm(runs, max(1, args.confirmations))
        if keys is None:
            print(f"  {format_unconfirmed(args.case, runs)}", file=sys.stderr)
            return 1
        Path(args.output).write_text(
            render_golden(args.case, keys, args.tool_version), encoding="utf-8"
        )
        note = "" if len(runs) <= args.confirmations else f" (after {len(runs)} runs)"
        print(f"  {args.case}: wrote {len(keys)} keys to {args.output}{note}")
        return 0

    if args.cmd == "check":
        expected = parse_golden(args.golden)
        actual = issue_keys(load_issues(args.guff), args.root)
        print(format_diff(args.case, expected, actual))
        missing, extra = diff(expected, actual)
        if not missing and not extra:
            return 0
        return check_ratchet(args.case, args.ratchet, len(missing), len(extra))

    return 2


if __name__ == "__main__":
    raise SystemExit(main())
