#!/usr/bin/env python3
"""Strict golden comparison for the check-level compat gate (Phase 3).

Unlike ``compat/normalize.py``, this module does **no** message normalization
and compares **column and severity** as well:

    key = path:line:col:linter:severity:text

``normalize.py`` exists to make two tools' *finding sets* collide across known
phrasing differences; that is the right trade for the OSS tier, where the goal
is "did we miss a finding". The golden tier asks a stricter question — "is the
rendered diagnostic byte-identical to golangci-lint's" — so every difference
that a user would see in their terminal must show up here, including the ones
``normalize_message`` deliberately erases (see COMPAT-HARDENING.md §5).

Goldens are generated by running golangci-lint itself (``regen.sh``); nobody
hand-writes an expected value, so no assumption can smuggle itself in.
"""

from __future__ import annotations

import argparse
import collections
import sys
from pathlib import Path
from typing import Iterable

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from normalize import is_related_information, load_issues, normalize_path  # noqa: E402


def escape(text: str) -> str:
    """Make ``text`` safe for a one-key-per-line golden file."""
    return text.replace("\\", "\\\\").replace("\n", "\\n").replace("\r", "\\r")


def issue_key(issue: dict, root: str) -> str:
    pos = issue["Pos"]
    path = normalize_path(pos["Filename"], root)
    return ":".join(
        (
            path,
            str(pos["Line"]),
            str(pos["Column"]),
            issue["FromLinter"],
            issue.get("Severity") or "",
            escape(issue.get("Text") or ""),
        )
    )


def sort_key(key: str) -> tuple:
    """Order a golden by source position, not lexically.

    Splitting from the left is safe: the golden's own paths never contain a
    colon (module-relative POSIX paths), and only the trailing message may.
    """
    path, line, col, rest = key.split(":", 3)
    return (path, int(line), int(col), rest)


def issue_keys(issues: Iterable[dict], root: str) -> list[str]:
    keys = [issue_key(i, root) for i in issues if not is_related_information(i)]
    return sorted(keys, key=sort_key)


HEADER = """\
# Golden finding set — generated, do not hand-edit.
#
# Regenerate with: ./compat/golden/regen.sh {case}
# Produced by running golangci-lint on compat/golden/cases/{case}/.
# key = path:line:col:linter:severity:text  (no normalization; \\n is escaped)
"""


def render_golden(case: str, keys: list[str], tool_version: str) -> str:
    lines = [HEADER.format(case=case), f"# golangci-lint: {tool_version}", "", *keys]
    return "\n".join(lines) + "\n"


def parse_golden(path: Path | str) -> list[str]:
    out: list[str] = []
    for raw in Path(path).read_text(encoding="utf-8").splitlines():
        line = raw.rstrip("\n")
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        out.append(line)
    return out


def diff(expected: list[str], actual: list[str]) -> tuple[list[str], list[str]]:
    """Return (missing, extra) as multisets: golden-only and guff-only keys."""
    exp, act = collections.Counter(expected), collections.Counter(actual)
    missing = sorted((exp - act).elements(), key=sort_key)
    extra = sorted((act - exp).elements(), key=sort_key)
    return missing, extra


def format_diff(case: str, expected: list[str], actual: list[str]) -> str:
    missing, extra = diff(expected, actual)
    n_both = len(expected) - len(missing)
    lines = [
        f"{case}: guff={len(actual)} golden={len(expected)} match={n_both} "
        f"missing={len(missing)} extra={len(extra)}"
    ]
    for k in missing:
        lines.append(f"  -golden {k}")
    for k in extra:
        lines.append(f"  +guff   {k}")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    sub = ap.add_subparsers(dest="cmd", required=True)

    p_write = sub.add_parser("write", help="Write a golden from a golangci-lint JSON dump")
    p_write.add_argument("--case", required=True)
    p_write.add_argument("--root", required=True)
    p_write.add_argument("--golangci", required=True)
    p_write.add_argument("--tool-version", default="unknown")
    p_write.add_argument("-o", "--output", required=True)

    p_check = sub.add_parser("check", help="Compare a guff JSON dump against a golden")
    p_check.add_argument("--case", required=True)
    p_check.add_argument("--root", required=True)
    p_check.add_argument("--guff", required=True)
    p_check.add_argument("--golden", required=True)

    args = ap.parse_args(argv)

    if args.cmd == "write":
        keys = issue_keys(load_issues(args.golangci), args.root)
        Path(args.output).write_text(
            render_golden(args.case, keys, args.tool_version), encoding="utf-8"
        )
        print(f"  {args.case}: wrote {len(keys)} keys to {args.output}")
        return 0

    if args.cmd == "check":
        expected = parse_golden(args.golden)
        actual = issue_keys(load_issues(args.guff), args.root)
        print(format_diff(args.case, expected, actual))
        missing, extra = diff(expected, actual)
        return 1 if (missing or extra) else 0

    return 2


if __name__ == "__main__":
    raise SystemExit(main())
