// Package after puts the marker *after* the package clause. Upstream parses
// with `parser.PackageClauseOnly|parser.ParseComments` and joins every comment
// group the parser collected, and the parser reads one token past the clause —
// so whether this file counts as generated is a question about the parser, not
// about the marker.
package after

// Code generated by guff's compat fixtures. DO NOT EDIT.

func mkerr() error { return nil }

// Run has one unchecked error.
func Run() {
	mkerr()
}
