// Code generated by qtc from "gen.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line gen.qtpl:1
package linedirective

//line gen.qtpl:7
func mkerr() error { return nil }

// Run has one unchecked error, written at a position a `//line` directive
// renames. Reporting it against `gen.qtpl` — which is what
// `fset.Position` answers — puts it in a file that carries no "Code generated"
// header, so `exclusions.generated` cannot see it either; golangci-lint's
// `FilenameUnadjuster` maps the position back to this file before anything
// looks at it.
//
//line gen.qtpl:12
func Run() {
//line gen.qtpl:13
	mkerr()
}
