[package]
name = "guff-goversion"
description = "A Rust port of Go's internal/goversion package (the Go 1.x version currently in development)."
keywords = ["go", "version", "port"]
categories = ["development-tools"]
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "guff_goversion"
path = "src/lib.rs"
