#!/usr/bin/env python3
"""Regenerate crates/guff-comment/src/godoclint_stdlib.rs from godoc-lint's
checked-in stdlib.json.

    python3 scripts/gen-godoclint-stdlib.py \
        "$(go env GOMODCACHE)/github.com/godoc-lint/godoc-lint@v0.11.2"

The JSON is godoc-lint's own build artifact, produced by running its
internal/gen analyzer over one specific Go source tree and then *checked into
its repository*. Regenerating it from a local toolchain would change the
symbol set — and therefore the finding set — for any Go release other than the
one upstream used. This script only transcribes; it never re-derives.
"""
import json, os, sys

# Upstream's SymbolKind also has an "" (SymbolKindNA) member, whose title is
# "symbol". No entry in any released stdlib.json has used it, so the Rust enum
# does not carry a dead variant for it — this mapping raises instead, which
# turns a future upstream change into a regeneration failure rather than a
# silently wrong diagnostic.
KIND = {"c": "Const", "v": "Var", "f": "Func", "m": "Method", "t": "Type"}
# The Rust enum is `StdlibSymbolKind`; `SymbolKind` is already taken by the
# declaration model, which answers a different question (func vs. everything).


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    gdl, out = sys.argv[1], sys.argv[2]
    version = os.path.basename(gdl.rstrip("/"))
    src = os.path.join(gdl, "pkg/check/stdlib_doclink/stdlib.json")
    with open(src) as f:
        data = json.load(f)

    lines = [
        "//! Generated by `scripts/gen-godoclint-stdlib.py`; do not edit.",
        "//!",
        f"//! godoc-lint's `pkg/check/stdlib_doclink/stdlib.json`, transcribed, from",
        f"//! `{version}`.",
        "//!",
        "//! That file is upstream's own build artifact: it was produced by running",
        "//! godoc-lint's `internal/gen` analyzer over one Go source tree and then",
        "//! checked into its repository. `require-stdlib-doclink` reports a symbol",
        "//! only if it is in this table, so regenerating the table from a local Go",
        "//! toolchain would change the finding set for every Go release but the one",
        "//! upstream happened to use. Bump it when godoc-lint bumps it, not when Go",
        "//! moves.",
        "",
        "use super::godoclint::StdlibSymbolKind;",
        "use StdlibSymbolKind::*;",
        "",
        "/// `(import path, package name, symbols sorted by name)`, sorted by import",
        "/// path. Both levels are binary-searched.",
        "///",
        "/// The package name is not always the last path element — `math/rand/v2` is",
        "/// `rand` — which is why upstream carries it separately.",
        "#[rustfmt::skip]",
        "pub(super) const STDLIB: &[(&str, &str, &[(&str, StdlibSymbolKind)])] = &[",
    ]
    for path in sorted(data):
        pkg = data[path]
        syms = pkg["symbols"]
        lines.append(f'    ({path!r}, {pkg["name"]!r}, &['.replace("'", '"'))
        row = []
        for name in sorted(syms):
            kind = syms[name]
            if kind not in KIND:
                raise SystemExit(
                    f"{path}.{name}: unknown symbol kind {kind!r}; add it to KIND "
                    f"and to StdlibSymbolKind in godoclint.rs"
                )
            row.append(f'("{name}", {KIND[kind]})')
        # pack a few per line to keep the file readable-ish
        for i in range(0, len(row), 4):
            lines.append("        " + ", ".join(row[i : i + 4]) + ",")
        lines.append("    ]),")
    lines.append("];")
    lines.append("")
    with open(out, "w") as f:
        f.write("\n".join(lines))
    print(f"{out}: {len(data)} packages, {sum(len(p['symbols']) for p in data.values())} symbols")
    return 0


if __name__ == "__main__":
    sys.exit(main())
