//go:build ignore

// Regenerates the two generated files under
// crates/guff-ast/src/doc/comment/ from the Go toolchain on PATH:
//
//	unicode_tables.rs — exact range tables for the four `unicode` predicates
//	                    go/doc/comment consults (IsLetter, IsUpper, IsDigit,
//	                    IsPunct). Rust's std offers the *derived properties*
//	                    Alphabetic / Uppercase / Numeric, which are supersets,
//	                    and has no equivalent for category P at all.
//	std_pkgs.rs       — go/doc/comment/std.go's list of standard library
//	                    packages with single-element import paths.
//
// Run from the repository root, with the same Go release golangci-lint was
// built with (`golangci-lint version` reports it):
//
//	go run scripts/gen-doccomment-tables.go
//
// Then re-run `cargo test -p guff-ast --test doc_comment`: the upstream txtar
// corpus is the check that the regenerated tables still agree with Go.
package main

import (
	"bytes"
	"fmt"
	"go/doc/comment"
	"os"
	"runtime"
	"strings"
	"unicode"
)

const outDir = "crates/guff-ast/src/doc/comment"

type rng struct{ lo, hi uint32 }

// ranges collects the scalar values at or above 0x80 for which f holds.
// The ASCII half is handled inline by the emitted Rust, which is both faster
// and easier to read than a table lookup.
func ranges(f func(rune) bool) []rng {
	var out []rng
	for r := rune(0x80); r <= 0x10FFFF; r++ {
		if !f(r) {
			continue
		}
		if n := len(out); n > 0 && out[n-1].hi == uint32(r)-1 {
			out[n-1].hi = uint32(r)
			continue
		}
		out = append(out, rng{uint32(r), uint32(r)})
	}
	return out
}

func table(b *bytes.Buffer, name string, rs []rng) {
	fmt.Fprintf(b, "#[rustfmt::skip]\nstatic %s: &[(u32, u32)] = &[\n", name)
	for i, r := range rs {
		if i%6 == 0 {
			b.WriteString("    ")
		}
		fmt.Fprintf(b, "(0x%X,0x%X),", r.lo, r.hi)
		if i%6 == 5 || i == len(rs)-1 {
			b.WriteString("\n")
		}
	}
	b.WriteString("];\n\n")
}

func genUnicode() []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, `// Generated by scripts/gen-doccomment-tables.go — DO NOT EDIT.
//
// Exact range tables for the four `+"`unicode`"+` predicates that Go's
// `+"`go/doc/comment`"+` parser consults: IsLetter (category L), IsUpper (Lu),
// IsDigit (Nd) and IsPunct (P). Source: %s `+"`unicode`"+` tables, walked
// scalar value by scalar value.
//
// Rust's `+"`char::is_alphabetic`"+` / `+"`is_uppercase`"+` / `+"`is_numeric`"+` are the
// *derived properties* Alphabetic / Uppercase / Numeric, supersets of the
// categories Go tests, and std has no category-P predicate at all. Storing a
// delta against std would silently rot the day Rust bumps its Unicode version,
// so these tables are absolute.
//
// Only the non-ASCII half is tabulated; callers handle ASCII inline.

/// Binary-searches an ascending, non-overlapping range table.
fn in_ranges(table: &[(u32, u32)], c: u32) -> bool {
    table
        .binary_search_by(|&(lo, hi)| {
            if c < lo {
                core::cmp::Ordering::Greater
            } else if c > hi {
                core::cmp::Ordering::Less
            } else {
                core::cmp::Ordering::Equal
            }
        })
        .is_ok()
}

`, runtime.Version())

	table(&b, "LETTER", ranges(unicode.IsLetter))
	table(&b, "UPPER", ranges(unicode.IsUpper))
	table(&b, "DIGIT", ranges(unicode.IsDigit))
	table(&b, "PUNCT", ranges(unicode.IsPunct))

	// The ASCII arms are spelled out rather than derived, so that a reader can
	// check them against Go by eye. gen verifies them below.
	b.WriteString(`/// Go ` + "`unicode.IsLetter`" + `: reports whether ` + "`c`" + ` is in category L.
pub(super) fn is_letter(c: char) -> bool {
    if c.is_ascii() {
        return c.is_ascii_alphabetic();
    }
    in_ranges(LETTER, c as u32)
}

/// Go ` + "`unicode.IsUpper`" + `: reports whether ` + "`c`" + ` is in category Lu.
pub(super) fn is_upper(c: char) -> bool {
    if c.is_ascii() {
        return c.is_ascii_uppercase();
    }
    in_ranges(UPPER, c as u32)
}

/// Go ` + "`unicode.IsDigit`" + `: reports whether ` + "`c`" + ` is in category Nd.
pub(super) fn is_digit(c: char) -> bool {
    if c.is_ascii() {
        return c.is_ascii_digit();
    }
    in_ranges(DIGIT, c as u32)
}

/// Go ` + "`unicode.IsPunct`" + `: reports whether ` + "`c`" + ` is in category P.
pub(super) fn is_punct(c: char) -> bool {
    if c.is_ascii() {
        return matches!(
            c,
            '!'..='#' | '%'..='*' | ','..='/' | ':' | ';' | '?' | '@' | '['..=']' | '_' | '{' | '}'
        );
    }
    in_ranges(PUNCT, c as u32)
}
`)
	return b.Bytes()
}

// checkASCII fails the generator if the hand-written ASCII arms above stop
// matching Go, which is the one part of the emitted file a human wrote.
func checkASCII() error {
	asciiPunct := ""
	for r := rune(0); r < 0x80; r++ {
		if unicode.IsPunct(r) {
			asciiPunct += string(r)
		}
	}
	const want = "!\"#%&'()*,-./:;?@[\\]_{}"
	if asciiPunct != want {
		return fmt.Errorf("ASCII punctuation changed: %q != %q — update is_punct's matches! arm", asciiPunct, want)
	}
	for r := rune(0); r < 0x80; r++ {
		if unicode.IsLetter(r) != ('a' <= r && r <= 'z' || 'A' <= r && r <= 'Z') {
			return fmt.Errorf("ASCII IsLetter changed at %q", r)
		}
		if unicode.IsUpper(r) != ('A' <= r && r <= 'Z') {
			return fmt.Errorf("ASCII IsUpper changed at %q", r)
		}
		if unicode.IsDigit(r) != ('0' <= r && r <= '9') {
			return fmt.Errorf("ASCII IsDigit changed at %q", r)
		}
	}
	return nil
}

func genStdPkgs() []byte {
	// go/doc/comment does not export the list, but DefaultLookupPackage is a
	// membership test over it, so probe every plausible single-element import
	// path from the toolchain's own package index.
	var names []string
	for _, name := range stdCandidates() {
		if _, ok := comment.DefaultLookupPackage(name); ok {
			names = append(names, name)
		}
	}
	var b bytes.Buffer
	fmt.Fprintf(&b, `// Generated by scripts/gen-doccomment-tables.go — DO NOT EDIT.
//
// The %s standard library packages whose import path is a single element, and
// which therefore could not otherwise be named in a doc link (go/doc/comment's
// std.go). Upstream keeps this sorted and binary-searches it; so does
// `+"`is_std_pkg`"+`.

#[rustfmt::skip]
static STD_PKGS: &[&str] = &[
`, runtime.Version())
	for i, n := range names {
		if i%6 == 0 {
			b.WriteString("    ")
		}
		fmt.Fprintf(&b, "%q,", n)
		if i%6 == 5 || i == len(names)-1 {
			b.WriteString("\n")
		} else {
			b.WriteString(" ")
		}
	}
	b.WriteString("];\n\n/// Go `isStdPkg`.\npub(super) fn is_std_pkg(path: &str) -> bool {\n    STD_PKGS.binary_search(&path).is_ok()\n}\n")
	return b.Bytes()
}

// stdCandidates lists the single-element import paths to probe, read straight
// out of $GOROOT/src so a new package in a future release is picked up.
func stdCandidates() []string {
	entries, err := os.ReadDir(runtimeGOROOT() + "/src")
	if err != nil {
		panic(err)
	}
	var out []string
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		name := e.Name()
		if strings.ContainsAny(name, ".") || name == "cmd" || name == "internal" || name == "vendor" {
			continue
		}
		out = append(out, name)
	}
	return out
}

func runtimeGOROOT() string {
	if v := os.Getenv("GOROOT"); v != "" {
		return v
	}
	return runtime.GOROOT()
}

func main() {
	if err := checkASCII(); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
	for name, data := range map[string][]byte{
		"unicode_tables.rs": genUnicode(),
		"std_pkgs.rs":       genStdPkgs(),
	} {
		path := outDir + "/" + name
		if err := os.WriteFile(path, data, 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "error:", err)
			os.Exit(1)
		}
		fmt.Println("wrote", path)
	}
}
