//go:build ignore

// Adds a `-- gofmt --` section (go/doc/comment's Printer.Comment output) to
// every txtar fixture under the given directory that lacks one, using the
// Parser hooks upstream's own TestTestdata installs.
//
// 18 of the 53 files copied from $GOROOT/src/go/doc/comment/testdata exercise
// only the html / markdown / text printers, none of which this crate ports.
// Without a gofmt section they would sit in the corpus asserting nothing; with
// one generated by Go itself they assert upstream's real answer.
//
//	go run scripts/gen-doccomment-gofmt-sections.go \
//	    crates/guff-ast/tests/testdata/doc_comment
//
// Idempotent: a file that already has a gofmt section is left untouched.
package main

import (
	"bytes"
	"fmt"
	"go/doc/comment"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	dir := os.Args[1]
	files, _ := filepath.Glob(filepath.Join(dir, "*.txt"))
	var p comment.Parser
	p.Words = map[string]string{
		"italicword": "",
		"linkedword": "https://example.com/linkedword",
	}
	p.LookupPackage = func(name string) (string, bool) {
		if name == "comment" {
			return "go/doc/comment", true
		}
		return comment.DefaultLookupPackage(name)
	}
	p.LookupSym = func(recv, name string) bool {
		return recv == "Parser" && name == "Parse" ||
			recv == "" && name == "Doc" ||
			recv == "" && name == "NoURL"
	}

	for _, file := range files {
		data, err := os.ReadFile(file)
		if err != nil {
			panic(err)
		}
		src := string(data)
		if strings.Contains(src, "\n-- gofmt --\n") || strings.HasPrefix(src, "-- gofmt --\n") {
			continue
		}
		input, ok := section(src, "input")
		if !ok {
			panic("no input in " + file)
		}
		input = strings.ReplaceAll(input, "$\n", "\n")
		var pr comment.Printer
		out := pr.Comment(p.Parse(input))
		// Re-add the trailing-space markers upstream uses, so the fixture
		// survives editors that strip trailing whitespace.
		var b bytes.Buffer
		for _, line := range strings.SplitAfter(string(out), "\n") {
			if line == "" {
				continue
			}
			body := strings.TrimSuffix(line, "\n")
			if body != strings.TrimRight(body, " \t") {
				b.WriteString(body + "$\n")
			} else {
				b.WriteString(line)
			}
		}
		if !strings.HasSuffix(src, "\n") {
			src += "\n"
		}
		src += "-- gofmt --\n" + b.String()
		if err := os.WriteFile(file, []byte(src), 0o644); err != nil {
			panic(err)
		}
		fmt.Println("added gofmt section:", filepath.Base(file))
	}
}

// section returns the body of the named txtar section.
func section(src, name string) (string, bool) {
	marker := "-- " + name + " --\n"
	i := strings.Index(src, marker)
	if i < 0 {
		return "", false
	}
	if i > 0 && src[i-1] != '\n' {
		return "", false
	}
	rest := src[i+len(marker):]
	for j := 0; j < len(rest); {
		k := strings.Index(rest[j:], "\n-- ")
		if k < 0 {
			return rest, true
		}
		line := rest[j+k+1:]
		if e := strings.Index(line, "\n"); e >= 0 {
			line = line[:e]
		}
		if strings.HasSuffix(line, " --") {
			return rest[:j+k+1], true
		}
		j += k + 1
	}
	return rest, true
}
