//! Generic id-indexed arena.
//!
//! `guff-types` hand-writes one arena struct per kind, but go/ssa has many
//! small object kinds (functions, blocks, instructions, params, ...), so we use
//! a single generic `Arena<Id, T>` parameterized by a typed handle. The handle
//! newtypes are generated by `def_id!` in [`crate::ids`] and implement
//! [`ArenaId`].

use std::marker::PhantomData;

/// Trait implemented by every arena handle newtype (see `def_id!`).
///
/// Handles are `NonZeroU32` and 1-indexed so `Option<Id>` stays 4 bytes.
pub trait ArenaId: Copy {
    /// Build the handle for the element at `index` (0-based) in an arena.
    fn from_index(index: usize) -> Self;
    /// The 0-based arena index this handle addresses.
    fn index(self) -> usize;
}

/// A `Vec`-backed arena addressed by a typed [`ArenaId`] handle.
///
/// Mirrors the `alloc`/`get`/`get_mut` shape of `guff-types`' arenas.
#[derive(Debug, Clone)]
pub struct Arena<Id: ArenaId, T> {
    items: Vec<T>,
    _marker: PhantomData<fn() -> Id>,
}

impl<Id: ArenaId, T> Default for Arena<Id, T> {
    fn default() -> Self {
        Arena {
            items: Vec::new(),
            _marker: PhantomData,
        }
    }
}

impl<Id: ArenaId, T> Arena<Id, T> {
    pub fn new() -> Self {
        Self::default()
    }

    /// Insert `value` and return a stable handle to it.
    pub fn alloc(&mut self, value: T) -> Id {
        let id = Id::from_index(self.items.len());
        self.items.push(value);
        id
    }

    pub fn get(&self, id: Id) -> &T {
        &self.items[id.index()]
    }

    pub fn get_mut(&mut self, id: Id) -> &mut T {
        &mut self.items[id.index()]
    }

    pub fn contains(&self, id: Id) -> bool {
        id.index() < self.items.len()
    }

    pub fn len(&self) -> usize {
        self.items.len()
    }

    pub fn is_empty(&self) -> bool {
        self.items.is_empty()
    }

    pub fn values(&self) -> impl Iterator<Item = &T> {
        self.items.iter()
    }

    pub fn values_mut(&mut self) -> impl Iterator<Item = &mut T> {
        self.items.iter_mut()
    }

    /// Iterate over `(handle, &value)` pairs in insertion order.
    pub fn iter(&self) -> impl Iterator<Item = (Id, &T)> {
        self.items
            .iter()
            .enumerate()
            .map(|(i, v)| (Id::from_index(i), v))
    }

    /// Iterate over `(handle, &mut value)` pairs in insertion order.
    pub fn iter_mut(&mut self) -> impl Iterator<Item = (Id, &mut T)> {
        self.items
            .iter_mut()
            .enumerate()
            .map(|(i, v)| (Id::from_index(i), v))
    }
}
