package gen

import (
	"fmt"
	"log"
)

type named struct{}

func (named) String() string { return "" }

type str string

func mixed(n named, s str, b []byte) {
	_ = fmt.Sprintf("%s", n)        // S1025, String(): not filtered upstream
	_ = fmt.Sprintf("%s", s)        // S1025, underlying string: filtered
	fmt.Print(fmt.Sprintf("%d", 1)) // S1038, fmt.Print: filtered
	log.Print(fmt.Sprintf("%d", 1)) // S1038, log package: not filtered
	_ = b
}

// Code generated by exp. DO NOT EDIT.
