// Code generated by guff's compat fixtures. DO NOT EDIT.

// Package strict carries the marker in the form Go itself defines
// (`^// Code generated .* DO NOT EDIT\.$` before the package clause), so both
// `generated: lax` and `generated: strict` treat it as generated.
package strict

func mkerr() error { return nil }

// Run has one unchecked error.
func Run() {
	mkerr()
}
