// Code generated by cmd/cgo; DO NOT EDIT.

// The one generator `RedundantTypeInDeclarationChecker` names:
//
//	gen, _ := code.Generator(pass, decl.Pos())
//	if gen == generated.Cgo {
//	    // TODO(dh): remove this exception once we can use UsesCgo
//	    return
//	}
//
// It matters because cgo's preamble writes `var _cgo0 *_Ctype_char = cPath`
// and the positions map back onto the call in the *original* file, so the
// findings escape the generated-file exclusion and land on a hand-written line.
// beats' `auditbeat/module/file_integrity/fileorigin_darwin.go:95` collected
// three guff-only rows pointing at one `C.getxattr(…)`.
//
// This file needs no cgo: `code.Generator` reads the header comment, which is
// what a real cgo output carries. The case that materializes it turns the
// generated-file exclusion off, or neither tool would look at it at all.
package cgo

func fromCgo() {
	var y *int = new(int) // silent — cgo
	_ = y
}
