#!/usr/bin/env python3
"""Generate a single-linter golangci-lint v2 config for the isolate harness.

Usage:
  python3 compat/isolate/make_config.py errcheck
  python3 compat/isolate/make_config.py errcheck -o /tmp/errcheck.yml
  python3 compat/isolate/make_config.py decorder --settings fixtures/decorder/settings.yml
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover - PyYAML optional; fall back to text merge
    yaml = None  # type: ignore


TEMPLATE = """\
# Auto-generated by compat/isolate/make_config.py — do not edit by hand.
# Single-linter isolate config for: {linter}
version: "2"

linters:
  default: none
  enable:
    - {linter}
{settings_block}
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  # Full finding-set compare (avoid SA#### vs S#### order winning uniq-by-line).
  uniq-by-line: false

run:
  timeout: 5m
  tests: true
"""

# golangci-lint v2 moved the formatters out of `linters:` into a block of their
# own, so `linters.enable: [gofmt]` is a config error rather than a no-op. This
# is why `golines` and `swaggo` sat in docs/COVERAGE.md with no isolate target:
# not a missing fixture, a template that could not name them.
#
# `linters.default: none` with only formatters enabled is a valid config —
# golangci-lint runs the formatters and exits 1 on a diff.
FORMATTER_TEMPLATE = """\
# Auto-generated by compat/isolate/make_config.py — do not edit by hand.
# Single-formatter isolate config for: {linter}
version: "2"

linters:
  default: none

formatters:
  enable:
    - {linter}
{settings_block}
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false

run:
  timeout: 5m
  tests: true
"""

FORMATTERS = ("gci", "gofmt", "gofumpt", "goimports", "golines", "swaggo")


def _indent(text: str, prefix: str) -> str:
    return "".join(prefix + line if line.strip() else line for line in text.splitlines(True))


def make_config(linter: str, settings: dict | None = None) -> str:
    name = linter.strip()
    if not name or any(c.isspace() for c in name):
        raise ValueError(f"invalid linter name: {linter!r}")
    template = FORMATTER_TEMPLATE if name in FORMATTERS else TEMPLATE
    settings_block = ""
    if settings:
        if yaml is None:
            raise RuntimeError("PyYAML required to embed settings overlays")
        # settings file is the body under linters.settings (may be {linter: {...}}
        # or a bare options map for this linter).
        if name in settings and isinstance(settings[name], dict) and len(settings) == 1:
            body = settings
        elif name in settings:
            body = {name: settings[name]}
        else:
            body = {name: settings}
        dumped = yaml.safe_dump(body, default_flow_style=False, sort_keys=False)
        settings_block = "  settings:\n" + _indent(dumped, "    ")
        if not settings_block.endswith("\n"):
            settings_block += "\n"
    return template.format(linter=name, settings_block=settings_block)


def load_settings(path: Path | None) -> dict | None:
    if path is None:
        return None
    if not path.is_file():
        raise FileNotFoundError(path)
    if yaml is None:
        raise RuntimeError(f"PyYAML required to load settings from {path}")
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if data is None:
        return None
    if not isinstance(data, dict):
        raise ValueError(f"settings file must be a mapping: {path}")
    return data


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("linter", help="golangci-lint linter name to enable alone")
    p.add_argument("-o", "--output", type=Path, default=None, help="write YAML here")
    p.add_argument(
        "--settings",
        type=Path,
        default=None,
        help="optional YAML fragment merged under linters.settings",
    )
    args = p.parse_args(argv)
    text = make_config(args.linter, load_settings(args.settings))
    if args.output is None:
        sys.stdout.write(text)
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
