// This file was automatically generated by foogen
package gocritic

import (
	"flag"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"sync"
)

// BadCommentFormatting has no space after //.
var _ = 0

// deprecated: use newer.
func deprecatedBad() {}

type orderIface interface {
	M()
}

type orderConcrete struct{}

func (orderConcrete) M() {}

func caseOrderBad(x interface{}) {
	switch x.(type) {
	case orderIface:
		_ = 1
	case orderConcrete:
		_ = 2
	}
}

func sloppyTypeAssertBad(r interface{}) interface{} {
	return r.(interface{})
}

func elseIf(cond1, cond2 bool) {
	if cond1 {
		println("a")
	} else {
		if cond2 {
			println("b")
		}
	}
}

func singleCase(x int) {
	switch x {
	case 1:
		println(1)
	}
}

func defaultMiddle(x int) {
	switch x {
	case 1:
		println(1)
	default:
		println("d")
	case 2:
		println(2)
	}
}

func switchTrue() {
	switch true {
	case true:
		println("t")
	}
}

func sloppy(s []int) {
	_ = len(s) >= 0
	_ = len(s) < 0
	_ = len(s) <= 0
}

func unslice(s []int) {
	_ = s[:]
}

func newDeref() {
	_ = *new(bool)
}

func appendAssign(xs, ys []int) {
	xs = append(ys, 1)
}

func dupCase(x int, ys []int) {
	switch x {
	case ys[0], ys[1], ys[0]:
		println(x)
	}
}

func captLocal(IN int) (OUT int) {
	return IN
}

func exitDefer(name string) {
	defer os.Remove(name)
	log.Fatal("boom")
}

func ifElseChain(a, b, c bool) {
	if a {
		println(1)
	} else if b {
		println(2)
	} else {
		println(3)
	}
}

func valSwap(x, y int) {
	tmp := y
	y = x
	x = tmp
}

func flagDeref() {
	_ = *flag.Bool("b", false, "docs")
}

func badCall(s string) {
	_ = append([]byte(nil))
	_ = filepath.Join("only")
	_ = strings.Replace(s, "a", "b", 0)
}

type execCtx struct{ id string }

func (c execCtx) GetID() string { return c.id }

// `.Where(m["x"].Pure)`: rewriting to `++` would call the getter once instead
// of twice, so upstream leaves it alone (dapr `taskexecutionid/single.go`).
func assignOpImpureIndex(m map[string]int, c execCtx) {
	m[c.GetID()] = m[c.GetID()] + 1
}

// A conversion *is* pure, so this one is still a finding.
type execCount int

func assignOpConversionIndex(m map[execCount]int, k int) {
	m[execCount(k)] = m[execCount(k)] + 1
}

func assignOp(x int) {
	x = x + 1
	x = x * 2
}

func underef(p *struct{ N int }) {
	_ = (*p).N
}

// `checkStarExpr` refuses a pointer to an interface or to another pointer: the
// dereference is not removable there. gitea keeps its indexers in an
// `atomic.Pointer[Indexer]` over an interface and writes `(*p.Load()).Close()`
// fourteen times, none of them a finding upstream.
type underefIface interface{ Close() error }

func underefPtrToInterface(p *underefIface) error {
	return (*p).Close()
}

func underefPtrToPointer(p **struct{ N int }) int {
	return (*p).N
}

func dupArg(a string) {
	_ = strings.Contains(a, a)
}

func dupBranch(cond bool) {
	if cond {
		println("same")
	} else {
		println("same")
	}
}

func dupSub(x int) {
	_ = x < x
}

func flagNameBad() {
	_ = flag.Bool(" foo ", false, "docs")
}

func mapKeyBad() {
	_ = map[string]int{
		"foo":  1,
		"bar ": 2,
	}
}

func offBy1(xs []int) {
	_ = xs[len(xs)]
}

func typeSwitchVar(v interface{}) int {
	switch v.(type) {
	case int:
		return v.(int)
	default:
		return 0
	}
}

func badCondFor(n int) {
	for i := 0; i > n; i++ {
		_ = i
	}
}

func badCondExpr(x, a, b int) {
	_ = x == a && x == b
}

func unlambda(fn func(int) int) {
	_ = func(x int) int { return fn(x) }
}

func regexpMust() {
	_, _ = regexp.Compile("abc")
}

func wrapperFunc(s string, wg *sync.WaitGroup) {
	_ = strings.SplitN(s, ",", -1)
	wg.Add(-1)
}

func argOrder(s string) {
	_ = strings.HasPrefix("#", s)
}
