// Code generated by hand. DO NOT EDIT.
package gocritic

import (
	"flag"
	"fmt"
	"regexp"
	"strings"
	"sync"
)

// Properly spaced comment.
var _ = 0

// Deprecated: use okNewer.
func okDeprecated() {}

type okOrderIface interface {
	M()
}

type okOrderConcrete struct{}

func (okOrderConcrete) M() {}

func okCaseOrder(x interface{}) {
	switch x.(type) {
	case okOrderConcrete:
		_ = 1
	case okOrderIface:
		_ = 2
	}
}

func okSloppyTypeAssert(r interface{}) interface{} {
	return r
}

func okElseIf(cond1, cond2 bool) {
	if cond1 {
		println("a")
	} else if cond2 {
		println("b")
	}
}

func okSwitch(x int) {
	switch x {
	case 1:
		println(1)
	case 2:
		println(2)
	default:
		println("d")
	}
}

func okSwitchTagless(cond, other bool) {
	switch {
	case cond:
		println("ok")
	case other:
		println("other")
	}
}

func okLen(s []int) {
	_ = len(s) == 0
	_ = len(s) > 0
}

func okSlice(s []int) {
	_ = s
	_ = s[1:]
}

func okNew() {
	_ = new(bool)
}

func okAppend(xs []int) {
	xs = append(xs, 1)
	_ = xs
}

func okCapt(in int) (out int) {
	return in
}

func okAssign(x int) {
	x++
	x *= 2
	_ = x
}

func okUnderef(p *struct{ N int }) {
	_ = p.N
}

func okDupBranch(cond bool) {
	if cond {
		println("true")
	} else {
		println("false")
	}
}

func okDupSub(x, y int) {
	_ = x < y
}

func okFlagName() {
	_ = flag.Bool("ok", false, "docs")
}

func okMapKey() {
	_ = map[string]int{
		"foo": 1,
		"bar": 2,
	}
}

func okOffBy1(xs []int) {
	if len(xs) > 0 {
		_ = xs[len(xs)-1]
	}
}

func okTypeSwitchVar(v interface{}) int {
	switch x := v.(type) {
	case int:
		return x
	default:
		return 0
	}
}

func okBadCondFor(n int) {
	for i := 0; i < n; i++ {
		_ = i
	}
}

func okUnlambda(fn func(int) int) {
	_ = fn
}

func okRegexpMust() {
	_ = regexp.MustCompile("abc")
}

func okWrapper(s string, wg *sync.WaitGroup) {
	_ = strings.Split(s, ",")
	wg.Done()
}

func okArgOrder(s string) {
	_ = strings.HasPrefix(s, "#")
}

func okEmptyString(s string) {
	_ = s == ""
	_ = s != ""
}

func okEmptyFallthrough(i int) {
	switch i {
	case 0, 1:
		_ = i
	}
}

func okOctal() {
	_ = 0o755
}

func okNilReturn(err error) error {
	if err == nil {
		return nil
	}
	return err
}

func okYoda(p *int) {
	if p == nil {
	}
	if *p == 10 {
	}
}

func okDefer() {
	defer fmt.Println("hello")
}

func okInit() {
	sideEffectOk()
	if true {
	}
}

func sideEffectOk() {}

