//! Differential test for `gostd::time` against Go's own `time.Parse`.
//!
//! `testdata/gostd/time_parse.tsv` is generated by `compat/oracles/gotime`,
//! which runs the real standard library over the same corpus. Nothing here is
//! hand-written, so the port cannot drift into an approximation that merely
//! looks plausible — the failure mode the SA1002 heuristic had for years.
//!
//! Regenerate with `compat/oracles/regen.sh gotime`.

use guff_staticcheck::gostd;

const GROUND_TRUTH: &str = include_str!("testdata/gostd/time_parse.tsv");

fn unhex(s: &str) -> Vec<u8> {
    assert!(s.len() % 2 == 0, "odd-length hex field: {s:?}");
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).expect("hex field"))
        .collect()
}

#[test]
fn parse_matches_go_on_every_corpus_layout() {
    let mut rows = 0usize;
    let mut errors = 0usize;
    let mut mismatches = Vec::new();

    for (lineno, line) in GROUND_TRUTH.lines().enumerate() {
        if line.is_empty() {
            continue;
        }
        let mut fields = line.splitn(3, '\t');
        let display = fields.next().expect("quoted layout");
        let hex = fields.next().unwrap_or_else(|| panic!("line {}: no hex field", lineno + 1));
        let want = fields
            .next()
            .unwrap_or_else(|| panic!("line {}: no error field", lineno + 1));

        let layout = unhex(hex);
        rows += 1;
        if !want.is_empty() {
            errors += 1;
        }

        let got = gostd::time::parse_bytes(&layout, &layout)
            .err()
            .map(|e| e.to_string())
            .unwrap_or_default();
        if got != want {
            mismatches.push(format!(
                "  layout {display}\n    go:   {want:?}\n    guff: {got:?}"
            ));
        }
    }

    assert!(rows > 9000, "ground truth looks truncated: {rows} rows");
    assert!(
        errors > 3000,
        "ground truth has too few error rows to be a real differential: {errors}"
    );
    assert!(
        mismatches.is_empty(),
        "{} of {rows} layouts disagree with Go:\n{}",
        mismatches.len(),
        mismatches
            .iter()
            .take(40)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}
