//! Differential tests for `gostd::template` against Go itself.
//!
//! `testdata/gostd/template_parse.tsv` is generated by `compat/oracles/gotemplate`,
//! which runs the real `text/template` and `html/template`. Nothing here is
//! hand-written.
//!
//! Regenerate with `compat/oracles/regen.sh gotemplate`.

use guff_staticcheck::gostd;

const GROUND_TRUTH: &str = include_str!("testdata/gostd/template_parse.tsv");

fn unhex(s: &str) -> Vec<u8> {
    assert!(s.len() % 2 == 0, "odd-length hex field: {s:?}");
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).expect("hex field"))
        .collect()
}

#[test]
fn parse_matches_go_on_every_corpus_template() {
    let mut rows = 0usize;
    let mut errors = 0usize;
    let mut reported = 0usize;
    let mut mismatches = Vec::new();

    for (lineno, line) in GROUND_TRUTH.lines().enumerate() {
        let mut fields = line.split('\t');
        let section = fields.next().expect("section");
        if section != "parse" {
            continue;
        }
        let hex = fields
            .next()
            .unwrap_or_else(|| panic!("line {}: no hex field", lineno + 1));
        let want = fields
            .next()
            .unwrap_or_else(|| panic!("line {}: no text/template field", lineno + 1));
        let want_html = fields
            .next()
            .unwrap_or_else(|| panic!("line {}: no html/template field", lineno + 1));
        assert_eq!(
            want, want_html,
            "html/template disagrees with text/template on this input, so one port \
             cannot serve both; see gostd::template's doc comment"
        );

        let raw = String::from_utf8(unhex(hex)).expect("corpus inputs are UTF-8");
        rows += 1;
        if !want.is_empty() {
            errors += 1;
            if want.contains("unexpected") || want.contains("bad character") {
                reported += 1; // the subset SA1001 actually reports
            }
        }

        let got = gostd::template::parse(&raw).err().unwrap_or_default();
        if got != want {
            mismatches.push(format!(
                "  input {raw:?}\n    go:   {want:?}\n    guff: {got:?}"
            ));
        }
    }

    assert!(rows > 1500, "ground truth looks truncated: {rows} rows");
    assert!(
        errors > 1000,
        "ground truth has too few error rows to be a real differential: {errors}"
    );
    assert!(
        reported > 300,
        "too few rows reach the messages SA1001 reports: {reported}"
    );
    assert!(
        mismatches.is_empty(),
        "{} of {rows} templates disagree with Go:\n{}",
        mismatches.len(),
        mismatches
            .iter()
            .take(40)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}

/// `unicode.IsLetter` and `IsDigit` decide where an identifier, field or
/// variable ends, so they are checked over the whole rune space rather than
/// sampled — the same treatment `strconv.IsPrint` gets in `gostd_url.rs`.
#[test]
fn letter_and_digit_match_go_for_every_rune() {
    let mut letter = vec![false; 0x11_0000];
    let mut digit = vec![false; 0x11_0000];
    let (mut letter_ranges, mut digit_ranges) = (0usize, 0usize);

    for line in GROUND_TRUTH.lines() {
        let mut fields = line.split('\t');
        let section = fields.next().expect("section");
        if section != "letter" && section != "digit" {
            continue;
        }
        let lo = u32::from_str_radix(fields.next().expect("lo"), 16).expect("lo hex");
        let hi = u32::from_str_radix(fields.next().expect("hi"), 16).expect("hi hex");
        let (table, count) = if section == "letter" {
            (&mut letter, &mut letter_ranges)
        } else {
            (&mut digit, &mut digit_ranges)
        };
        for c in lo..=hi {
            table[c as usize] = true;
        }
        *count += 1;
    }

    assert!(
        letter_ranges > 100 && digit_ranges > 10,
        "range sections look truncated: {letter_ranges} letter, {digit_ranges} digit"
    );

    let mut mismatches = Vec::new();
    for n in 0..0x11_0000u32 {
        let Some(c) = char::from_u32(n) else {
            continue; // surrogate: not a Rust char, and excluded by the oracle
        };
        if gostd::unicode::is_letter(c) != letter[n as usize] {
            mismatches.push(format!(
                "  is_letter(U+{n:04X}) go={} guff={}",
                letter[n as usize],
                gostd::unicode::is_letter(c)
            ));
        }
        if gostd::unicode::is_digit(c) != digit[n as usize] {
            mismatches.push(format!(
                "  is_digit(U+{n:04X}) go={} guff={}",
                digit[n as usize],
                gostd::unicode::is_digit(c)
            ));
        }
    }

    assert!(
        mismatches.is_empty(),
        "{} disagreements with Go:\n{}",
        mismatches.len(),
        mismatches
            .iter()
            .take(40)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}

/// Go parses arbitrarily deep nesting because a goroutine stack grows; this
/// port is recursive-descent on a fixed stack, so it stops at
/// `gostd::template`'s own recursion limit instead of aborting the process.
///
/// The thread here is 2 MiB — a quarter of what guff's lint workers get — and
/// this test runs unoptimized, where a frame costs about four times what it
/// does in release. Before the limit existed, 1000 nested parens overflowed at
/// this size.
#[test]
fn deep_nesting_stops_instead_of_overflowing_the_stack() {
    for depth in [100usize, 1_000, 10_000, 100_000] {
        let input = format!(
            "{{{{print {}1{}}}}}{}{}",
            "(".repeat(depth),
            ")".repeat(depth),
            "{{if .}}".repeat(depth),
            "{{end}}".repeat(depth)
        );
        let joined = std::thread::Builder::new()
            .stack_size(2 * 1024 * 1024)
            .spawn(move || gostd::template::parse(&input).err())
            .expect("spawn")
            .join();
        let err = joined.unwrap_or_else(|_| panic!("depth {depth} crashed the thread"));
        match depth {
            100 => assert_eq!(err, None, "depth 100 is well within the limit"),
            _ => assert!(
                err.is_some_and(|e| !e.contains("unexpected") && !e.contains("bad character")),
                "past the limit guff must decline, and silently: SA1001 reports \
                 only those two classes"
            ),
        }
    }
}
