//! Differential tests for `gostd::regexp` against Go itself.
//!
//! `testdata/gostd/regexp_compile.tsv` is generated by `compat/oracles/goregexp`,
//! which runs the real `regexp.Compile`. Nothing here is hand-written.
//!
//! Regenerate with `compat/oracles/regen.sh goregexp`.

use guff_staticcheck::gostd::regexp::{compile_bytes, CompileResult};

const GROUND_TRUTH: &str = include_str!("testdata/gostd/regexp_compile.tsv");

fn unhex(s: &str) -> Vec<u8> {
    assert!(s.len() % 2 == 0, "odd-length hex field: {s:?}");
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).expect("hex field"))
        .collect()
}

fn show(b: &[u8]) -> String {
    String::from_utf8_lossy(b).into_owned()
}

#[test]
fn compile_matches_go_on_every_corpus_pattern() {
    let mut rows = 0usize;
    let mut errors = 0usize;
    let mut codes = std::collections::BTreeSet::new();
    let mut non_utf8 = 0usize;
    let mut mismatches = Vec::new();

    for (lineno, line) in GROUND_TRUTH.lines().enumerate() {
        let mut fields = line.split('\t');
        let quoted = fields
            .next()
            .unwrap_or_else(|| panic!("line {}: no quoted field", lineno + 1));
        let pattern = unhex(
            fields
                .next()
                .unwrap_or_else(|| panic!("line {}: no pattern field", lineno + 1)),
        );
        let want = unhex(
            fields
                .next()
                .unwrap_or_else(|| panic!("line {}: no result field", lineno + 1)),
        );

        rows += 1;
        if std::str::from_utf8(&pattern).is_err() {
            non_utf8 += 1;
        }
        if !want.is_empty() {
            errors += 1;
            // "error parsing regexp: <code>: `<expr>`" — take the code alone,
            // so the tally counts distinct failure modes rather than distinct
            // patterns.
            let text = show(&want);
            if let Some(rest) = text.strip_prefix("error parsing regexp: ") {
                if let Some((code, _)) = rest.split_once(": `") {
                    codes.insert(code.to_string());
                }
            }
        }

        let got = match compile_bytes(&pattern) {
            CompileResult::Valid => Vec::new(),
            CompileResult::Invalid(msg) => msg,
            CompileResult::Undecided => {
                mismatches.push(format!(
                    "  pattern {quoted}\n    go:   {:?}\n    guff: <undecided>\n    \
                     no corpus row may hit the recursion limit",
                    show(&want)
                ));
                continue;
            }
        };
        if got != want {
            mismatches.push(format!(
                "  pattern {quoted}\n    go:   {:?}\n    guff: {:?}",
                show(&want),
                show(&got)
            ));
        }
    }

    assert!(rows > 3000, "ground truth looks truncated: {rows} rows");
    assert!(
        errors > 1000,
        "ground truth has too few error rows to be a real differential: {errors}"
    );
    // Every parse error `regexp/syntax` can produce, less ErrInternalError
    // (unreachable by construction) and ErrInvalidCharClass (declared but never
    // returned by parse.go).
    assert_eq!(
        codes.len(),
        14,
        "the corpus should reach every reachable ErrorCode, got: {codes:?}"
    );
    assert!(
        non_utf8 > 100,
        "too few ill-formed inputs to exercise ErrInvalidUTF8: {non_utf8}"
    );
    assert!(
        mismatches.is_empty(),
        "{} of {rows} patterns disagree with Go:\n{}",
        mismatches.len(),
        mismatches
            .iter()
            .take(40)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}

/// Go's parser is iterative over the input but recursive over the tree it
/// builds, and a goroutine stack grows to fit. This one runs on a fixed stack,
/// so past its own limits it returns `Undecided` — and SA1000 reports nothing
/// for that, because unlike SA1001 it has no whitelist to fall outside of.
///
/// The thread is 2 MiB, a quarter of what guff's lint workers get, and this
/// test runs unoptimized where a frame costs several times what it does in
/// release. Both recursions are driven, because they have different limits and
/// only one of them may go quiet:
///
/// * Nested groups walk the tree. Go rejects these above its own `maxHeight`,
///   and guff has to *agree* rather than decline — at any depth.
/// * A chain of ever-longer shared prefixes drives `factor`, whose frames are
///   an order of magnitude fatter. Beyond its limit guff declines.
#[test]
fn deep_nesting_stops_instead_of_overflowing_the_stack() {
    fn on_a_small_stack(input: String) -> CompileResult {
        std::thread::Builder::new()
            .stack_size(2 * 1024 * 1024)
            .spawn(move || compile_bytes(input.as_bytes()))
            .expect("spawn")
            .join()
            .expect("the point of the limits is that this never crashes")
    }

    // Go's own answer for these three is pinned by the corpus (999 compiles,
    // 1000 does not); past that the depth stops mattering to Go and must not
    // start mattering to guff either.
    for depth in [1_000usize, 2_000, 100_000] {
        let nested = format!("{}a{}", "(".repeat(depth), ")".repeat(depth));
        let got = on_a_small_stack(nested);
        assert!(
            matches!(&got, CompileResult::Invalid(m) if show(m).contains("nests too deeply")),
            "{depth} nested groups: guff must still reach Go's verdict, got {got:?}"
        );
    }

    // Past MAX_FACTOR_DEPTH. Go says `expression nests too deeply` here; guff
    // declines instead, which costs a finding on input no one writes and never
    // invents one. n=8000 is past where the rune budget bites first, so Go and
    // guff agree again.
    for n in [1_000usize, 3_000] {
        let prefixes = (1..=n).map(|k| "a".repeat(k)).collect::<Vec<_>>().join("|");
        assert_eq!(
            on_a_small_stack(prefixes),
            CompileResult::Undecided,
            "a {n}-deep shared-prefix chain must decline, not abort"
        );
    }
    let wide = (1..=8_000usize)
        .map(|k| "a".repeat(k))
        .collect::<Vec<_>>()
        .join("|");
    assert!(
        matches!(on_a_small_stack(wide), CompileResult::Invalid(m) if show(&m).contains("too large")),
        "the rune budget bites before factor recurses, so this one is decided"
    );
}
